theme: minima
title: Skilled Reflection
description: Keep a skilled eye on yourself.
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
