---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

# PPL  

46. Author's note: The concepts in this chapter are under active development. 
47. Numbers 48-53 would be the basis for a revised chapter. 

1.	Think of PPL (PPL) as seeds that clarify and cultivate your garden or 
affect your garden in other ways.
2.	Maybe they are your friend, and need help with some unruly vines, or 
maybe you just like their apples. Sometimes, PPL are like water, 
bringing extra life to needy crops. 
3.	Sometimes PPL are careless and track weeds in on their boots, or over-
encourage your interests until you sprain an ankle, or come to your 
garden and distract you, make you anxious or bored or excited. How 
are PPL affecting your garden?
4.	Everything that happens in their garden could be thought of as a seed 
in yours.
5.	How much TIME your visit takes and what you get are like TIME spent 
on a plot of soil of that person, and the fruit that comes of your TIME.

6.	Where do you get seeds for FOOD from and how did you know to 
plant them? 
7.	From other PPL, right? No silly, you don't know how to garden a 
sandwich! 
8.	Lucky for you, many of the most important crops, products, and 
savings are already grown, prepared and handed to you--in exchange 
for money, which you have from spending TIME on a much larger, 
collective garden called society, doing some very specialized thing 
called WORK. 

## WORK  

9.	You'll WORK about 80,000 hours in your life in exchange for already 
grown apples and baked CAKE, and a toilet to take your poop 
somewhere else.

10.	WORK pays the broadest insurance: money. 
11.	Money is traded for maintenance of SELF and CAKE. 
12.	It takes 80,000 hours of your TIME.
13.	WORK is made to serve NORMS, not you.

14.	Relatedly, NORMS assume you will WORK for money for goods. 
15.	NORMS are all actions assumed of (or about) the "average" person.
16.	Language, agreed usage of WORDS, is made from NORMS.
17.	NORMS may or may not always be the most reliable way for you.
18.	NORMS are the web of FORCES of all actions of all PPL, including 
WORK, religion, popular attitudes, and DOUBTS.
19.	When you are individual, NORMS push against you.

20.	A FORCE is any cause of change. 
20.1.	A FORCE underlies every action involved in a GOAL, yours or 
otherwise.
20.2.	There are forces within your control, and forces outside.
21.	MAINTENANCE is the COST of FORCE to neither move toward nor 
away from a GOAL. 
22.	ALIGNMENT is when NORM or natural FORCE causes your GOAL to be 
more likely.
22.1.	To ALIGN is to adjust your GOAL to be more like another force, 
usually one acting against your GOAL. 
22.2.	Study how forces WORK against you. 

23.	Relationships (RLTP) are GOALS about PPL (PPL). 
24.	Good ones are aligned with your GOALS.
25.	Bad ones COST more. 
26.	A RLTP is a reciprocal pair of BETS, yours of them, and vice versa.
27.	RLTPS, especially family members, coordinate many GOALS for 
SAVINGS.

28.	Pick WORK and RLTP that maximize your other PRIS including possibly 
one that maximizes TIME and money to apply to other PRIS.
29.	Pick friends the same way. 
30.	Consider your actions and choices about PPL carefully. 
31.	Maximally ALIGN with NORMS with least compromise to PRIS. 
32.	ALIGN (get along) with PPL.

## The Classroom  

**Note: If this section is confusing, revisit it after "Ed".**  

33.	(No one chose to be born.) 
34.	Everyone begins life with their own unnamed and unanswered 
problems.
35.	Books can only tell a student what the answer is not (quite).
36.	The gap between problem and book answers is left for the student to 
"apply".
37.	A better approach would be to let the student define the problem 
through their reality and life GOALS.
38.	Let them write the PLAN and teach them only what is needed to 
succeed.
39.	Imagine a perfect course exists, designed to teach you to fulfill your 
specific ambitions. 
40.	Every aspect of what you NEED to know, that is known and 
communicable, is the only thing written. 
41.	Everything that cannot be known but must be discovered or practiced, 
is laid out as a set of instructions, described in the WORDS that 
maximize the learning opportunity, and your progress.
42.	Rather than a course in a classroom, the perfect class is a manual to 
reference as you live your life, or at least until you've internalized its 
contents: 
43.	when to take a break to strategize your decisions, lessons on what 
opportunities to watch for and resist, and so on. 
44.	Any social role you wish to take on, artist, engineer, therapist, 
insurance salesperson, reliable partner, is customized intimately, 
curated perfectly for what you need.
45.	Any relationship or interpersonal skill that is realistically possible for 
you is preceded with the guidance and education that prepares you 
emotionally to choose the right experiences that set you up to be 
most likely to find and make the most of opportunities to share 
yourself with another.

48. People, are the part of a theory of life that require the most care, and least words. 
49. Unlike the nature of our actions which play unconsciously and imply bets, 
50. Common, bad people activity is the habit of over-emphasizing mutual bets, and 
51. which fall out of alignment with actions.
52. Instead, consider a relationship to be only the actions that are reciprocated;
53. and call this the relationship 'contract.'

