---
output:
  word_document: default
  pdf_document: default
  html_document: default
---


# Epilogue

## Reader Opt-in 

1.	Now you have read this book. 
2.	What were your numbers? (6.50)
3.	Annotate 100 lines you would bet 1 dollar on each, and you are an IBC student.
3.1.	Your bets would go to a general pool.
3.2.	When bets on a line reach a critical mass, the pool of subpar bets is split 
among winners.
3.3.	Cash is divided.
3.4.	Also, points are recorded, to incentivize a deeper purpose:
3.5.	A game, where the prize is
3.6.	the collective revision and authorship of this book.
3.7.	After x wins, your name appears on the title.
3.8.	High scores are on the acknowledgements page.
3.9.	This is the process and meaning of READER and WRITER; bound directly to 
material and action, IRL.

## Your Calling, Part II 

4.	Tell me the missing chapter
that gives peace instead of regimen,
so that I may find mine.

## Prequel to Answerword 

`comm-by-instructor0 to-instructors`  
`i-"By the instructor of instructors, to instructors."`  

5.	Listen up, you vibrating sacks of meat.
6.	A teacher and student conspire in a radical co-dependency, mutually betting on 
the student's ability. 
7.	It is my job to sniff out why on Earth you are interested in this.
8.	You are crazy for wanting to be a teacher. 
9.	Until you are, you have only one thing to teach: 
10.	You must teach me to believe you.
11.	You will do everything to put the truth in front of me.
12.	If I find out you withhold the truth, I will punish you with it.
13.	You are a teacher when your student has paid for both your TIME.

## Beginnings

14. If you need more examples to make more sense of this book, read the second, "Answerword". 
15. If you need to stand beyond the limits of both, prepare with the third and last book, "Lastword".

