
# Define Yourself

## Routine and Ideal
65.	You are how you act. Therefore, establish a baseline to know what it will take to 
get where you want to be.
66.	One of the most common mistakes of planning is being overly optimistic in 
predicting outcomes.
67.	This exercise is a remedy.

68.	Task 1. 5m, 50w. Take five minutes to produce the WORDS that are most likely 
to accomplish your GOALS for the day. This may include describing the GOALS, 
the PLAN, and/or the DOUBTs.
69.	Task 2. 5m, 50w. Copy those 50 WORDS and revise them according to the 
following instruction.
69.1.	Replace "accomplish your GOALS" with "do". 
69.2.	In 50 WORDS, what should you (or an all-knowing observer) BET on that 
you will do, today? 
69.3.	Regardless of what you assumed in Response one, do not write with the 
intention of 'motivating' yourself, but to simply describe your day. 
69.4.	If this is too hard, simply evaluate what you did yesterday.
70.	Task 3. 5m, 0w. Compare your responses. Positive differences (more optimistic) 
in your first response reflect bets you are making against your habits.

### SELF-750

71.	How accurately can you describe yourself? 
72.	Relate to those who care, including your better SELF, by practicing the right 
WORDS.

#### SELF-past  

73.	Task 1. 20m, 250w. Look back on your life. What are your CAKE, and where did 
they come from?

#### SELF-future

74.	Where are you going? Imagine your life plays out 
74.1.	Ideally.
74.2.	Terribly.
74.3.	Typically.
75.	Consider 1. What could go right or wrong, 2. What it depends on and the 
likelihood. 3. Who you will be if it happens.
76.	Create a "choose your adventure", ordered by likelihood.
77.	For example, (I will:)  80% make enough money to be content. 50% marry, and 
- 50:50 ends well or in divorce, and 10% major accident leading to depression.

#### SELF-now  

78.	Task 3. 20m, 250w. Make a small table with three columns. 
79.	In the 1st column, leave enough room in the first column for a short text 
description, and a 1-2 digit number for the 2nd and 3rd column.
80.	Think about a day and how much TIME you spend on various activities, averaged 
over 365 days in a year.
81.	on-daily activities such as visiting the dentist should be factored in, accordingly. 
82.	List the activities in the first column.
83.	List the TIME you spend (in hours), in the second column. 
84.	The total of your second column should be 24.
85.	Task 3a. 2m, 50w. Choose a GOAL you named in SELF-Future with a probability 
of outcome that you would like to increase. 
86.	What change is needed in your daily schedule to make this increase?
87.	Estimate the re-allocation of TIME required to achieve your GOAL, in the third 
column. 
88.	For example, if your GOAL is to lose weight, you may need to adjust TIME for 
exercise and eat, and other activities if you "need more TIME".
89.	Task 3b. 3m, 50w. List most likely reasons this PLAN fails, especially reverting to 
old habits.
90.	Task 3c. 10m, 150w. Add steps to create and protect changes in your schedule.
91.	Task 3d. 1m, [decide-date]
92.	BET on this (Task 3b vs 3c). Set a date on the calendar to assess your 
commitment to this PLAN.

