---  
title: "Skilled Reflection-Strictly Content"  
version: 1.1  
output:  
  word_document:   
    reference_docx: template.docx  
  pdf_document: default  
  
---  
  
# overhead  

## Tagline  
Change your thoughts. Change your life.  

## Abstract  
  
Bet(Life) = Words / Time. 
Bets improve life. 
words mediate bets. 
Life has three inter-related dimensions. 
A person experiences the world with  
senses, holds BETS about the world, and 
commits ACTIONS on the world. 

Desired experiences are GOALS. 
Which (words) lead to success? 
To Plan (1) is human (2). 
Words (3) and numbers (4) are aids. 
Bets synthesize all four. 

Much like DOUBTS is a metonym for REALITY, 
PPL are a metonym for 
the forces that we co-exist with. 
1. Self: physical realities--  
sleep, nourishment, physical and mental fitness, health
---constrain time for 
actions and success of goals. 
2. Ppl: People have goals that can  
help or hinder. 
Work costs time but gives resources for goals. 
3. Pri: Actions take time, and 
time is limited. 
Goals are worth different amounts. 
How will you divide time across your goals?  
  
## Key words  
intellectual coaching, mind-training, defining goals, accountability, expanding the boundaries of the mind, personal development, redirecting your life, tapping into your capabilities, identifying and challenging limiting patterns of thought, accomplish goals, unlock abilities, tap into your potential, motivation  
  
# 02 Prefc - 600w  
  
Dear Friend,  
  
since I first wrote about 
the Intellectual Boot Camp (IBC) in 2017,  
I have felt as if I am forever awakening from a dream, 
slowly moving in a constant, 
panicked daze toward a still-clearer reality. 
From that first essay on, 
I have attached a GOAL and 
deadline to develop the IBC,  
in line with the theory's 
strong position on time management. 
From the first essay on, 
I have always been late.  
  
This book is my biggest attempt yet 
to shake myself from the dream of  
the IBC, and 
it is the most late of all of them. 
I undertook it after  
some key insights, and 
ould not put it together without discovering a  
few more, and 
now it is too far from complete 
for an excuse. 
Yet here it  
is in your hands anyway, because 
it is time. 
I hope you can enjoy some  
wonder beyond the morning breath of 
this half-awoken book. 
Thank you so much 
for being my friend.  
  
I respectfully ask you to 
please be as scathing and  
ruthless as possible 
in your critiques of 
the CONTENT of this book. 
If I've LINKED the core IDEAS correctly, 
your most cutting critiques will  
breathe even more life into the theory. 
  
each chapter begins with a short  
description of key points. 

The book is organized into 
three parts. 
Part One is on 
the learning and teaching context,
with definitions of 
instructor and student in the IBC. 

Part Two is the IBC's key IDEAS 
(words in all capital letters), 
presented logically, 
arranged by  topic. 

Figure 1 indexes most IDEAS and 
their basic associations,
shared here to reduce potential confusion with lay-definitions.
Most  
These are nuanced, but lay-definitions are generally okay on first-pass.

The third part of the book is 
a set of core lessons for applying core IDEAs
to your life.
  
My deepest gratitude goes to 
the first student of the boot camp, 
who so generously offered to publish this volume, and 
whose dream I have loved watching blossom.  
  
### Figure 1  
  
Figure 1. The relationship between core IDEAS of this book. These will  
appear throughout in capital letters, but are defined in context in Part  
Two. Here, terms are grouped according to chapter, to aid finding  
definitions and provide a first approximation of conceptual relationship  
between IDEAS. In both boxes, the first word in each row refers to a  
Chapter (except LIB, a section of COMM).  
  
### *Extra  
This is for you if:   
1.	you are going to die some day, and  
2.	it matters to you how you pass the time,  
3.	you want to maximize quality time, or   
4.	there is something worth living for.  
  
# 40 Gardn - 6700w  
  
**Part One**  
  
- IBC "Student 0"  
Narrative, historical "preface"  
Overlaps partially with #Plans  
  
- Bet  
Bet thesis in narrative form.  
  
- Garden  
Blank slate for conceptualizing PRIs.  
  
- Plans  
Description of problem and (IBC) solution,  
and definition of Instructor's Role.  
  
- School  
First approximation "skeleton plan" of IBC implementation,  
recruitment pitch, and   
Instr1- Commitment  
  
- SR  
Instr2- Reflection  
core method and logistics.  
  
## 08 IBC-v1 710  
"Student 0"  
  
I often have recurring dreams about   
the absurdity of military boot camp.  
I relive the sense of having a knife hand at my throat,   
scared shitless   
as the instructor spits profanity in my face.   
He'll do this again and again so that  
instead of just imagining,   
I can come to intuit   
a sense of discipline around   
whatever behavior set off his explosion.   
The instructor's resolved,   
intense belief is what allows a student to develop   
a deep, unique set of values.   
When I wake, I don't call these nightmares.  
  
For the 18-year-old Mark looking for discipline and drive,   
society didn't provide many options.   
The things Marines boot camp came with  
--countless hours of drill, combat training,   
military tactics and history--  
seemed necessarily entangled in the idea of discipline.  
  
But I don't need combat readiness anymore.   
My 18-year-old self didn't necessarily need it, either.   
I wanted to go to college, but   
was intimidated and beset by unaddressed fears.   
I didn't see any alternatives for gaining confidence and character.   
If only there was a course of training that   
prepared me to be a rigorous, productive, confident thinker,   
instead of combat.  
  
My experience in the Marines was both necessary and vital for who I am  
now, even as an academic, but it has also slowed me down.   
At best, combat training is a loose analogy to   
the mental work and discipline needed for intellectual pursuits.   
At worst, it's counterproductive and alienating.  
  
On the one hand, the military gave me an eye for practical solutions  
that align well with research goals.   
It is good tactical discipline to assess circumstances, cut out the excess, and evaluate possible outcomes in service of a quick, executable solution.  
  
On the other hand, the nature of battle is not like the nature of  
thinking (or debates, even).   
Assuming limited resources and taking an aggressive or defensive stance, is less helpful than accurately identifying   
similarities, differences, and possibilities for improvement.   
A lot of energy has been spent applying military notions of competition to my research.  
  
I want to see a boot camp whose purpose is to train young adults to  
think harder, clearer and more effectively;   
to produce intelligent, usable solutions to personal and social puzzles;   
to have a higher cognitive discipline;   
to instill shared values about   
reason, thinking and discourse; and   
ultimately, to empower strong individuals.  
  
Modeled after the instructor-student mentorship in military boot  
camp,   
this is a training program designed to   
break down bad habits of thought and   
build a more rigorous, disciplined, effective mind.   
Students would give up personal possessions, wear a uniform,  
adhere to a strict code of ethics, and   
in isolation from the outside world.  
  
The central experience of an IBC student would be intense,   
relentless intellectual challenging and confrontation of their own ideas about the  
world by instructors.   
This would be through drilling of intellectual skills (writing essays, arguing for ideas, and   
developing proposals for action) under pressure with limited resources (time, information, attention).   
They would be trained to focus   
in the face of perceptual, physical, or emotional distractions.   
Over time, students could expect to cultivate   
a sharper focus on cognitive objectives,   
resilience to distractions and challenges.   
like their own ego.  
  
Students would graduate with the ability   
to identify, develop, and communicate ideal critical,  
rational arguments,   
positions or plans (orally or written) given the available knowledge, finite time, and resources at hand   
(reference material, teamwork).   
Students would also learn responsible, ethical ways  
to interact in a broader community---leading, collaborating, and  
competing with existing systems of problems and solutions, subordinates,  
peers, and supervisors.  
  
The central requirement for applicants is a commitment to better  
understand the self and world.   
Students would leave with   
the capacity to handle a broad range of  
unforeseeable and foreseeable problems and goals.  
  
My waking hours have slowly been taken over by these ideas.   
I now dream of them.   
I don't have it all worked out;   
I don't even have all the skills I'd expect of students.   
What I have is the belief that   
an immersive, intense instructor-student model   
can sharpen minds in ways   
our education system is not designed to, and  
our society increasingly needs.  
  
## 08 BetLife 742  
  
You can take control of your life, or   
you can let the world bet for you.    
  
**Doubts. **  
When I was little I wanted to be a writer.   
I dreamed up stories and books.   
I imagined writing them, but 
I never picked up the habit.   

I wanted to be the one to 
inspire others by painting 
scenes that reflected reality in a new way, but 
I rarely wrote. 
Nearing high school graduation, 
the missing work was hard to ignore, and 
I accepted I wasn't a novelist.  

PLAN-
If you want your dreams to become real,    
listen to your doubts.  
  
My hesitation stemmed from 
doubts that I had what it  
took to be a writer. 
Eventually those doubts became reality. 
I was afraid to 
accept the work needed to 
achieve my dream. 
I needed to bet my life 
in order to learn this.  
  
**Bets. **  
I hated that I let myself down; that I never  
challenged my doubts. In that emotional frustration I felt confronted  
with the possibility that I was too weak to be inspiring at all. I put  
my life on the line to prove I wasn't afraid to succeed. I enlisted in  
the Marine Corps.  
  
I didn't know it then, but I had made my first serious bet. I forced a  
confrontation with the complacency that held me back from becoming  
somebody. I just had to survive my enlistment to win, and winning meant  
progress.  
  
I had pit my dream---to be a source of inspiration for others---against  
my doubts of pulling it off. The outcome of this would either clearly  
move me toward my goal, or push me to stop denying reality and adjust my  
expectations.  
  
When you bet your life, winning means your reality is one shade more  
like your goal. Losing is the wake-up call to be more realistic about  
your dreams. Betting is the instruction manual for how to pursue your  
dreams. It is also a reality-check for fantasies.  
  
Along with discipline came many stumblings that led to better  
self-awareness about how I might be suited to improve lives. Unlike my  
hesitation to write, I actually spent time helping others understand  
their values and achieve their goals. I wanted to be a psychologist.   
  
For this version of my dream, I set out to test it immediately. I  
started full time as a psychology major within weeks of finishing my  
enlistment. The proof was in the pudding. Studying wasn't work; it was  
play. I loved it. In three years, I was off to graduate school for a  
PhD.  
  
Bets, in this sense, are a way of committing your dreams to the facts of  
reality. This is importantly different from making your dreams come  
true. Bets don't make dreams real, because most dreams have elements of  
fantasy in them; something conceivable, but impossible.  
  
More accurately, betting is a protocol to guide you to reality, and if  
you're lucky, you might have some liberties to make your dreams fit in.  
  
How real will your dreams get before you die?  
  
**Lessons. **  
No really, consider it, right now. Imagine  
the most realistic, attainable, best life you could have. Imagine taking  
the first step and then stay with the thought. Listen to the fear that  
surfaces. For the moment, never mind how the world has gotten in your  
way. How are you in your own way? See your doubts with curiosity. Now  
bet on overcoming them.  
  
Congratulations, you've completed the first lesson of the Intellectual  
Boot camp.  
  
In the latest revision of my dream, I am an educator of bets.  
I've been betting on this technique for years now.   
First, I was my own student,  
and then I recruited friends and   
eventually University students.   
I've been making the idea of Bets into reality.  
  
I'm preparing to bet my life, again.   
I will need students willing to bet theirs,   
in order to build this school.  
  
*Maybe then I'll write that book.*\*  
Hey, a boy can BET, can't he?  
  
\*You're reading my first book.  
  
Learn about [[#Bets]] and   
complete [Lesson Seven](Self) to Bet your Life.  
  
## 04 Gardn 1090  
del90  
  
This thought experiment helps visualize your life goals,   
especially in terms of the time and actions required (PRI).  
  
Imagine your life is a garden. Every one of your life ambitions, GOALS,  
is buried in the ground as seeds.  
Finding a life partner, acquiring a car or promotion, or resolving a  
conflict with your childhood friend are all matters spread across the  
dirt in need of water, sunlight, and---most important---your time. Other  
goals, like naps, your favorite hobbies, or TV shows, take little work and  
grow almost anywhere.   
Whether they are dear to you or weeds,   
if they take your time, they are in your garden.  
  
Today, you are on one end looking out across the  
entire garden.   
What has already been planted? What will you add and how  
much time will you devote to those goals?   
Every seed you plant---  
even abstract ones like passing a course or making a friend---  
implies things in and out of your control (work and weather), beyond your  
awareness (the future), depending on the goal.  
  
Meditate on the final products of your garden.   
Is there a more important plant that deserves your time today?   
Meditate on the prioririties of your work.   
Do two plants grow better when together?   
Make a quick and accurate assessment, but   
don't sit here all morning thinking about it.  
What do you want to cultivate, today?  
What do you want to cultivate in this life?   
  
You want what your body and mind best respond to. Many of these seeds  
will be obvious. It is up to you how curious you are for what better  
life is possible. The only way to know is to make the best  
assessment you can about past outcomes to make predictions about what  
new seeds or gardening techniquest you should try. You don't have enough  
time in the day to tend to try everything, and many are not worth  
trying. There is not always harm to planting something that does not  
grow, but sometimes there is---you could run out of space, time, or  
energy that could have been devoted to better crops; you might get a  
weak yield for trying to grow something not suitable in your climate, or  
find you have no taste or stomach for the fruit.  
  
In the garden, the COSTS of goals are grounded in their most basic  
sense: time and attention.  
  
Every day, as a human, you spend time eating, drinking, pooping, and  
sleeping. You might make things that help you more efficiently manage  
your garden. Building a HOME provides SAVINGS for the basic needs of  
being human. In this contained environment, you can efficiently prepare  
and eat food, maintain hygiene, and sleep.  
  
If you don't have the SKILLS, you just need a PLAN, and time to practice  
and learn. Look on the internet, or go visit Dot's garden and see if you  
can trade something for his help. Just know that when you leave your  
garden, you are definitely not tending to it.  
  
*People*    
  
In someone else's garden, you have (only) what you see immediately  
before you, and their word about what came before.  
Maybe they are your friend, and he needs help with some unruly vines, or  
maybe you are captivated by some apples you haven't seen before.  
Everything that happens in their garden could be thought of as a seed in  
your garden: how much time your visit takes and what you're left with,  
after.  
  
Sometimes, people are like water, bringing extra life to needy crops.  
Sometimes people are careless and track weeds in on their boots, or  
over-water your interest in running until you sprain an ankle.  
Sometimes, people are like pills. Someone might come to your garden and  
distract you, make you anxious or bored or excited. How are the people  
(PPL) in your life affecting your garden?  
  
Where do you get seeds from and how did you know to plant them? From  
other people, right? No silly, you don't know how to plant all these  
plants! Lucky for you, many of the most important crops, products, and  
savings are already grown, prepared and handed to you---in exchange for  
money, which you have from spending time on a much larger, collective  
garden called society, doing some very specialized thing called WORK.  
You'll do about 80,000 hours of work in your life in exchange for  
already grown apples and baked cake, and things like toilets to take  
your poop somewhere else.  
  
The expectation that you will WORK for money for goods often falls  
outside your control (NORMS). NORMS are a reliable way to live,  
generally, but not necessarily the best, which goes back to that  
curiosity business mentioned earlier.  
  
Many people believe in seeds with special powers, like true love, or  
winning the lottery. One seed grows the duration of your life, which you  
rarely notice but are often aware of. When you eat it, the sun sets for  
the last time and you bite the dust. Think about this, but don't dwell  
on it. It happens to all of us.  
  
Instead, think of what you can grow from the seeds of the best apple in  
your crop, which you tended to with dedication and skill. Think of the  
seeds of people that clarify and cultivate your garden---Dot's cousin  
who also loves leatherworking seeds. Also, think of what's happening  
right this very moment: nothing in your garden, while you're sitting  
here thinking. Reflect only enough to improve your actions.  
  
Your garden allows you to ground the many goals of your life into a  
medium the mind is well-equipped to analyze: visual space. Maybe it  
seems unnecessary to represent work satisfaction and relationship  
quality in terms of carrots and tomatoes. When you arrive at the moment  
of boredom or frustration in attempting to put your life in terms of  
concrete IDEAS and actions between them (LINKS), ask yourself why you  
are bored and frustrated attempting to define the things that apparently  
define you. What is happening in your life, and what is in your control  
if these are unclear? If you are not reflecting on your life, your  
garden is a foggy labyrinth and you are a drunk gardener wearing  
oven-mitts.  
  
# 06 IBC    
The IBC idealized.  

## Pitch
### toEducation 143  

REALITY-
Widespread education failure
begins with answers purported
by a few authors far removed from
the students' PRIs and PLANs
(questions and answers).

EXAMPLE-
The PLAN for happiness is  
within reach for all, except
in books and WORDS
by a few others (authors),
thus, with idiosyncratic STYLE.

BOOK relevance and application 
is left to the student.

Books tell a student 
what the answer is not.

A student begins with 
problems that do not have names,
not those named in books. 

Define knowledge by   
the student's reality and life goals.  

The only book 
should be a PLAN template
- robust across individuals,  
- self-learnable,  
- iterable and  
authored by the population.
i-this book.

LINK-toApplicant
It begins with the average answer
to the following invitation.

### toApplicant 89w  
  
How would your life look 
if you put it on paper?    
How do you get what you  
need and want?   
How do you clarify and 
direct your life?   

With better words.   
The right words will change 
your actions and your life.  
It's time to live a better life.   
It starts with your words,  
and a commitment to change.  
  
Committing is a personal decision, and risk.   

1.Is there a better version of you?  
2.Are you capable of moving toward it?  
3.Are you ready?  

Then apply.

LINK-toINSTR
\*Such a program does not exist,
until the following call
for an instructor is met.

### toINSTR 0 212  
<!-- imagined as the introduction to the -->
<!-- instructor's course;  -->
<!-- whereas standard swim qual is -->
<!-- an objective test of water commitment, -->
<!-- the top level requires  -->
<!-- water skill despite  -->
<!-- an overt adversary. -->
  
Welcome,
You vibrating sack of meat   
taking up my space and time.  

i am the first student that demanded one, but 
i am your teacher, 
until you convince me otherwise.  

you say 
you want to be a teacher, so
you are crazy.  
  
a teacher and student
take on a debt of time to
bet on my life;
a radical co-dependency. 
why would you do this?  
  
aggressive teaching is not logical, but 
you and i are not dealing with the logical. 
i must doubt you. 
  
you will do everything to 
put the truth in front of me.  
if i find out you withhold truth, 
i will punish you with it.  

you are a teacher when you 
re-do your shitty lecture, 
until your student has earned 
both your time.

LINK-toStudents
An instructor agrees,
because they BET: 

### toStudents 148  
2021-02-16  
  
your calling,  
your highest value,  
is yours to name;  
an idea about the world,  
bounded by reality and your doubts.  
  
if you overcome your doubts,  
and see reality plainly,  
you will want peace.*  
    
but we all have doubts, so   
you want some form of   
dignity and affirmation.  
    
tell me your calling, student,  
and subtracting from peace,  
i'll tell you your doubts.  
  
On finishing this book  
your life will be regimented  
to afford your calling.  
  
tell me the missing chapter  
that lets you achieve peace  
instead of a life of regimen,  
so that I may find mine.  
  
*time*  
The beginning is now,  
and the end is near.  
The rest is math.  
  
To master time is to   
attend to your life,   
in its passing degrees.  
  
*Congruence*  
parsimony is to   
maximize energy on priority 1 and   
0% toward others.   
Either sacrifice SELF pri (asceticism), or   
assign SELF as pri 1, Buddhism.   


## IBC Pedagogy  

### Apply-p 53  
PLAN-
Demonstrate you are minimally capable of   
identifying, cultivating, and   
communicating GOALS in writing, and   
hold genuine commitment to their growth (or quit).   
      
The interested applicant will:   
a. Submit a 400-word essay describing your goal(s) and   
   why coaching will help you.  
b. On receiving feedback, return a revised 400-word essay   
   within 48 hours.  
  
   
### -COST-p
#### material

7- or 30-day experience,  
meals and lodging included.  

REALITY-
Our bodies resist discomfort.   
You won't learn    
unless you cannot escape needing it;
in a dedicated environment   
that fosters acquisition,
minimizes interference.

EXAMPLE-
No phone or internet access.  

#### actions  

Students,  
0.provide two minutes of product  
  for every minute of learning. 
  a.content toward others' learning (IBC).  
  b.the application of their learning.  

Dedicate to identity growth. 
Be:  
  
1.  Quiet, except when tasks require verbal response.  
2.  Receptive to work and feedback provided by the instructor.  
3.  Committed to producing genuinely inspired ideas, working quickly,  
    and seeking improvement.  
4.  Respectful that all are equal in voice, and aim to describe  
    solutions with collective values.  
5.  Receptive and responsive to observations (from peers and/or  
    instructors) of their DOUBTS: vague language, cognitive bias,  
    illogical arguments, and over-valuing of personal arguments.  
6.  Motivated to describe solutions that benefit others, when possible.  

7. Respond to prompts on a computer   
enabled with a text editor,
document and time manager. 
8. provide work for other students' goals via  
anonymous peer-review. 

You will
- eat, sleep, think, talk, and act differently.
Your
- thoughts, 
- attitude, and    
- life will be different.


## PUSHED
### Phase-2 IBC 134

With these simple constraints on thought and written expression, individuals produce standardized documentation   
(individual problem identification,   
progress tracking including barriers) of   
authentic lives, motivations, and solutions, and   
critically, in timed, quantifiable sessions.   
The result is a recipe for well-controlled,   
context-rich data on   
the process of thinking about one's life.   
Those willing to volunteer their reflections and   
its efficacy on their lives  
are providing higher resolution views on   
the psychological landscape.   

The psychological landscape is   
not complete without the social landscape.  
  
The intellectual bootcamp is a controlled community 
aiming to catalyze learning.   
Here, the individual improves themselves
and helps others
on the bet that what goes around comes around.   

### Phase-3 63  

Ideally, insights from the IBC would lead to generalization to non-controlled environments and education systems.   
  
Phase three will exist only to the extent that   
a shared sentiment and belief exists,  
to increase the value in the self,  
and that a better life is possible,  
if we only commit ourselves and   
each other to trying to make it happen for ourselves,  
and each other.  

# 40 Laws 9660w  
**Part Two**  
  
An introduction to the foundation, 
best read slowly and in order. 
Refer to Figure 1 in the Preface to see 
LINKs between IDEAs.  
  
# DEFs 2388w
  
## BET
Betting maximizes getting what you need and want  
by imposing deadlines to confront   
costs, habits, unknowns and doubts.  
  
### GOAL
- names a problem,   
- comprises a PLAN for an ideal outcome, and   
- has COSTS associated with exercising the PLAN.   
- can be 
  - finite and singular or persistent and recurring.   
  - REALITY or FANTASY.  
  
### PLAN
any external suggestion   
(usually words) with the goal to  
improve the chance and   
decreases the costs of achieving your GOAL.  

Specific PLANs:   
1.  INSTR. Instructions for learning, making, changing, reminding.  
2.  DOC. Document-based GOALs, like manuscripts and resumes.  
  
PLAN templates:  
1.  LESSONs. A reflection plan. Read and complete steps in order.   
2.  TOOLs. Like a hammer, anti-virus software.  
  
### BET
PLAN template for   
reconciling REALITY with CHUD  
to accomplish GOALs.   

Successes shorten your PLAN, and   
the distance to your GOAL.  
Failures mean you underestimated  
your CHUD.   
  
Every IDEA you hold is a BET  
with a rolling deadline,   
idiosyncratic achievements,  
and inconsistent revisions.  

Figure 2. Bet schema.   
PLAN and DOUBT reflect predictions   
biased to assume the GOAL,   
action and CHUD will be reality or fantasy,  
respectively.   
Biases are updated when the deadline passes. 

## C.H.U.D. 86  


The degree you are wrong is UNKNOWNS.   
DOUBTs are the BET against yourself.  
  
### COSTS
COST is the amount of change needed   
(between your current and goal state)   
to accomplish a GOAL:  
labor and resources needed.   
All costs are variations of passing time.  
  
### HABITS
Your dominant tendencies (FORCES).   
Bad HABITS are FORCES working against your GOALS.  
Good HABITS are ALIGNED with GOALS.
  
### UNKNOWNS  
As long as you have not arrived at the goal, 
there are Unknowns.  
It is unclear if you can control it,  
but you can estimate it.  
Failures reveal DOUBTS.

The difference (error) between 
your Plan's estimate of reality,
and Reality.    
  
### DOUBTS  
Good DOUBTS temper  
an optimistic PLAN.
Bad DOUBTS fuel bad habits and fantasies.  
  
Fear, anxiety, and jealousy,  
reflect overestimation of UNKNOWNs.  
Resistance to change due to arrogance and ego   
reflect underestimation of UNKNOWNs.  
  
To be **distracted** from
or bored of
your plan is    
- anxiety about your future.  
- discomfort toward present reality.  
- distrust in your past. 

## Self
SELF is what's sufficient and necessary to survive.  
  
SELF is the direct effort to  
mitigate the cost of existing HABITs and DOUBTs;  
and optimize health  
to maximize your BETs.  
  
SELF optimizes bodily homeostasis   
- Eating,   
- sleeping,   
- pooping,   
- showering,   
- making babies, and   
- staying alive   
in order to maximize your values.  
   
SAVINGs intrinsic to your body, 
especially GOALS  
that are high MAINTENANCE. 

### (GROUPS)  
SELF is grouped by GOALs of your body:   
Being fed, well-rested, and unstressed.  
A HOME groups associated actions by place: 
storing food,  
providing running water, and protection from the elements.   

### HOME  
All physical material and  
resources you own, including MONEY; and
environment and basis for HABITS.

A good HOME is a PLAN for SELF;  
simplifying the GOALS of   
eating, sleeping, and other basic needs.   
A bad HOME facilitates bad HABITs.

### VALUES
Anything fulfilling,  
including the reason for living.   

## 04 Pri 177  
  
Managing the set of goals in your life is   
the goal of PRI.   
Betting your life, GOALs, and VALUEs are   
refined by and subservient to the full set  
of facts in your life, and   
the management of these.   

PRIs recognize that GOALs  
all draw from a single, finite  
source of attention, and   
a single, limited and finite existence;  
you.  

  
PRIs is your map to VALUES.  

  
### ORDER 142  

### REALITY  

PRIs shift around as you  
spend more time on one and not another.   

  
### SAVINGS  169  
completing an action  
that serves various goals.   
  


### GROUPS 217  
Grouping makes SAVINGs.
Figure 3 below illustrates savings  
from the good maintenance practice of grouping.   


Grouping works for  
abstract or concrete things.
Figure 3.   
SAVINGs are illustrated as a function of GROUPs,
across three rooms. The same OBJECTs are: 
As you find them (Room 1),   
labeled clearly (Room 2), and  
Grouped by function (Room 3).    
Letters reflect different things, and  
shape differences reflect different kinds of things.  



### GOALS-group
single outcome,
or sustained state (MAINTENANCE).

### RETIREMENT-group
time until you die;
resource and automation for 
remaining life COSTS.   
  
### TIME  

The constant or denominator for FORCES, FORGETTING,
PRI, and LIB.


## PPL

### FORCE  

cause of change.   
There are forces within your control, and   
forces outside your control.   

MAINTENANCE is what it costs 
to neither move toward nor away from a GOAL.   
RISKS are covered by INSURANCE. 

### Norms
NORMs pay out MONEY for WORK.  

Others' actions can impact your GOALs.   
NORMS are the web of FORCES of   
all actions of all people, including   
WORK, religion, popular attitudes, and DOUBTS.   
  
NORMS benchmark the COST of living.  

Individuality can conflict with NORMs.
PPL'S LANGUAGE is made from NORMS.
When you are individual, 
NORMS push against you
  
### Work  
WORK is made to serve NORMs, not you.
yet takes 80k hours of your time.

WORK pays the broadest INSURANCE: MONEY.   
Money is traded for MAINTENANCE of  
SELF and VALUES.   

### RLTP 
GOALs about PPL.   
you would spend much
to protect their SELF
and perhaps VALUEs.
Good ones are aligned,   
Bad ones cost you.   
RLTPs are reciprocal BETS,   
yours of them, and vice versa.  

### ALIGN  

Adjust direction of your goal to be more similar to another force,
usually one acting against your goal.
   
## Words 

Words can make you smarter.   
Words provide miniatures of reality that  
are efficient for exploring possibilities.  
You can think through 
far more situations with words, than 
you can (or should) try in reality.   
Your GOALs can be described in words, and 
words can be easily crossed out and revised, with minimal labor. 
Words increase the quality of decisions.   
  
The COST of an individual word is tiny, but   
we say tens of thousands per day.   
 
Words are BETS on hypotheticals. 
Reading, thinking, saying, and writing   
a word perpetuates that word's IDEA over others.   

WORDs reflect 
- truth and reality.
- lies and fantasy.
WORDs either push you toward a GOAL, or your HABIT.   

The WORDS BET is about maximizing productivity of thought.   
Mastering this is synonymous with being smarter.  

Words guide attention past local biases.  
Words do one thing well,   
if you trust them:   
move you out of local minima  
- distractions.  

Good words are ones that 
direct attention to PRIS, and 
predict reality. 

Any validation or assurance from words is brittle,   
because there is no  
reliable shared meaning.  
- Not "If I'm nice will you trust me?"  

### IDEAS  
### LINKS  

WORDs are one of two types:   
  
1.  IDEAS: words for things.  
2.  LINKS: words that give relationship between things. 

Together, these make up CONTENT 
(vs STYLE).  


### WORDS
A major culprit of wasted time
is wasted words.  

### NOTES  

It also distinguishes supporting 
from main BETS of an IDEA.
NOTES are PLANs to improve
clarity and value of WORDs for COMM.

1. a syntactic tree, where  
2. [newline] is the right path in a fork,  
3. first indent (" -") is the left path in a fork,  
   - trailing "-" denotes all subsequent lines 
     in section are equal childs.   
4. subsequent newline indents or in-line "--" are siblings  
5. left to right are siblings  
6. double linebreak ends the local tree.  
  
when word order is a left-to-right walk of 
a right-branching syntactic tree, 
sentence can be written in lines of random lengths, and 
read equally as unambiguously. 


  
         
  
### COMM  

COMM deals with the complexity of PPL and WORDs.   
COMM is the exchange of WORDS with other PPL.   
  
### COMM-PRI  

is-CONTEXT
Two people with identical PRIs see the world identically.  

### STYLE, VERSION  

PRIs between WRITER and READER differ.
Difference in PRIs alter CONTENT of IDEAs.

Good STYLE is change in WORDs to minimize change in IDEAs
between READER and WRITER.
  
VERSIONs describe identical CONTENT 
with difference in STYLE between them.   

you today vs you in five years (LIB).   


A PLAN for a DOC is an earlier VERSION of
the (same) final DOC.
  
Some STYLE addresses those who 
fail to appreciate READING and WRITING. 

NORMS (COMM-PPL) typically requires adding language and rearranging presentation order in a way that:  
  
1.  Strokes ego and intelligence of others;  
2.  Appears to rock no boats; and  
3.  Frames attacks as agreeable observations.  
  
SELF IDEAs are the most STYLE-free. 
e-FOOD and CAKE.

### BRAND  
STYLE that intentionally simplifies or obscures relevant  
LINKs to an IDEA. 

### RLTP--Peers

Peer review is a powerful learning tool.

The peer WRITER   
works with uncompromised objectivity,   
and liberty to employ Truth,   
however subjectively "harsh".  


## SR 

The value of words (meaning)
depends on TIME.
WRITING is for READING.
TIME passes between, so
DOC is subject to COMM issues.

The GOAL of words is to express IDEAs that 
will retain their value tomorrow.   

Work to make IDEAS clear and concrete. 
Put IDEAS at the top of a DOC.   
Provide just enough CONTEXT. 
to remember the basis of the key IDEAs.   
  
Precision depends on purpose.   

LINKS are BETS of 
higher risk and reward than IDEAS.   
  
The right LINK between IDEAs is 
the foundation of every thought, 
recipe or terrible calculation.   

IDEAs are BETs on LINKs 
between EXAMPLEs in the world.   



#### PROMPTS  171  
**Prompts ** elicit conflicts (truth) between SELF and  
NORM, to improve PLANS for your GOALS. TIME and WORD limits work  
together to encourage a balance between reflecting on truth and  
describing it.  


### DOCs  

DOCs revisited and revised later are 
better with fewer words. 

### WORD_CT
Word limits combat needless words and  
distracting tangents.  
A word limit keeps your attention.  

A DOC's word count is a proxy for 
its complexity; 


The **word limit** lets you succinctly address the prompt. Try to  
write the exact number of words. To meet word limits, you will need to  
cut out unhelpful words. When in doubt, remove figurative language and  
strive for words that are assertive and testable (falsifiable). In the  
following example, the shorter version is still figurative, but more  
assertive and clear:  
  
It breathes through your peers and  
neighbors, who speak a language  
of norms.  
  
4 Your peers and neighbors speak a language of  
norms.  

#### TIME
The **time limit** dictates how precise your words should be. Extra  
time is for better words. For example, a one-minute, 50-word limit (1m,  
50w) encourages free writing similar to the Dear Diary  
above, with minimal restrictions on quality of thought.  
Conversely, a 4-minute, 40-word limit (4m, 40w) is meant to encourage  
more careful selection of your words.  

#### LESSONS  144  
LESSONS are an ordered set of prompts, usually three to four, up to 60  
minutes and 250 words. In lessons, a prompt's word count is the number  
of words to be added to your document.  
  
The first prompts in LESSONS are 
warm-ups to direct your attention. 
They ask for names of IDEAS. 
  
The next prompts are for thinking, requiring you to make LINKS between  
your warm-up IDEAS. Done right, you will face some new truths. For  
example:  

### REVISE 238  
REVISION is how we know reflection is happening, described here in  
VERSIONS (v\#) of a response. Considering the Dear Diary  
example again:  
  
Ask yourself why you felt this conflict. What ingredients or  
instructions are fail-proof in causing you to have this reaction? 5m,  
20w.  
  
Response-v1:  
  
1.  I work hard on an intellectual activity.  
2.  I'm not secure about it.  
3.  Someone I admire undermines it.  
  
The issue starts out specific, but on reflection, generalizes. It relies  
on simpler observations making it more valuable for the future.  
  
Response-v2:  
  
1.  I make something I think is well done.  
2.  I expect validation.   
3.  Criticism catches me off guard.  
  
Note: A 0w prompt means revise, but do not increase the total word  
count.  
  
**Revise the prompt.**   
The prompts encourage reflection,  
but truth-seeking defines the prompt.   
While reflecting you may uncover  
truths less relevant to the prompt than to your GOALS.   
Revise the prompt  
in a way that best promotes development of the insight at hand.   
This may be toward the end, or on the first prompt.   
For example,   
a prompt referring to University student experiences   
should be adapted for your  
non-University experiences as relevant.  
  
Prompts and topics are designed to be challenging,  
but if they are emotionally overwhelming,   
Change the prompt.  
Do not change the prompt so you can be lazy.  
  
You should also revise answers to prior prompts, but   
only to keep up with or   
help address the current prompt.  
  
#### SAVE-if (LIB)  
f-identifies gap bx pris and habits  
  i-CAL  
  
vs-whereas WORDS deals with involuntary IDEAs,
LIB is the post-production cache to facilitate future production.

X-Lessons are only valuable for the insights  
that will make tomorrow helpful.   
Lessons are designed to be  
revised over time.  

### REALITY  

RECOGNITION, reading familiar WORDs is easier than   
RETRIEVAL from memory, of WORDs to write.   
is-an IDEA-REVISION SAVINGs.

### LIB  

The collection of your WORDs over a lifetime.   
A good LIB is the closest approximation of SELF.
`Library = sum(GOALS + PLANS) / 1`  
A bad LIB is the sum of your WORDS, void of curation.



### RISKs  

1.FALSE POSITIVE: Writing and saving and finding bad DOCs.
2.FALSE NEG: failure to save and find good DOCs.


### GOAL  

To learn about what you don't know you don't know.

## 06 Roles - 794w  

### ROLE  

 set of attitudes and actions.  
  
### READ  

listening to another person.   

Revisions beyond pronouns makes you a WRITER.
is-PLAN-
If you revise other words to maximize your BET,
you are a writer.

  
### WRITER  

 BET on WORDs.
A writer invests time and energy   
to map feelings onto words.   
  
Good writing is discovering,   
curating, and applying insight.   
Bad WRITING has an author; *ad hominem*   

### Student-d  

Students are PPL with
IDEAS from EXPERIENCE toward 
selfish GOALS. 

Lessons depend on 
students' prior knowledge.   

A STUDENT 
  
1.  has a goal that can be better named and planned.  
2.  requires time away from BETTING on my Goal.  
3.  admits not knowing but capable.

A bad student studies 
to avoid living, or 
for its own sake.
  
X-Environment
To learn a thing, 
a student need only  
be in an environment that 
VALUES a shared knowledge.   

### BET  

Good COMM and LIB-PPL maximize utility of PRI-PLANs.

3.Students learn to represent their knowledge in words.   
They learn to prefer better, alternative  
representations, especially from peer reviews.  


### INSTR-d
A guardian of 
1.True IDEAs expressed in COMM, and
2.WRITER of a general PLAN (this book).


### Scientist    
  
A scientist WORKs to win BETS against the UNKNOWN. They are a  
professional writer, evaluated on two metrics:  
  
1.  For their MEMES of CONTENT.  
2.  The net benefit of their MEMES on GOAL outcomes.  
  
A scientist-researcher is a WRITER,   
a data-collector and hypothesis tester.   
A scientist-scholar is a READER,  
curating toward theory development and COMM.  
  
### Scholar  

 interpreter of  
others' self-truth, a Peer-Reviewer professional,  
by incorporating the Scientist's insights.  

evaluated by repost statistics   
(others as readers),  
akin to evaluating twitter users by their retweets.  
  
  
# WORDS-STYLE
The only thing more complex than PPL and facts are WORDS.   
PPL and facts are IDEAS and WORDS are their LINKs.   
PPL and all their actions are limited to a single Reality whereas WORDs are not.  
The challenge and wonder of WORDs is to see what they are,   
having BET on WORDS that facilitate Reality.   
What will language (and __fluency__) look like   
grounded in empirical Truth?   


## LESSONS
### HERE and NOW-INTRO

There are two kinds of people in this room.  
To the first kind of person  
you are encouraged to embrace yourself,  
honestly, and seriously; to investigate who you  
are, and strengthen your grounding in this world.   
To the  
second kind of person, you learn to spend your time  
more effectively, and get more of it.   
Both kinds of you need the same  
core ideas: attention, thinking, time, and truth.  

### HERE and NOW-END


Identity makers,   
try not to waste time.   
Time hackers, try not to waste space.   



# PLANS

## BETS  
### PLAN   


### BETS  
  

### DEF-TIME
deadline
- time

  
### CHUD  

Account for true COSTS and HABITS 
in your way to achieve a GOAL;   

### SELF  

#### VALUES  


## PRI

### SAVINGS  

### DEF-GROUPS  

RLTPs, especially family members, coordinate many GOALS for SAVINGS.  

#### LIB

### TIME  
  

## PPL-DEF
Others and the relationships with them define   
the BETS called people (PPL).  

### FORCE

  
### RLTP

### ALIGN
  

## WORDS  

### NOTES  

Add tags as a prefix to the dash 
to make the nature of the LINK  explicit.  
Prefixes are not exhaustive or mutually exclusive  
  
1.  `e` example, data-point, untested data  
2.  `x` Cross-references, xref  
3.  `d` Data or evidence, summary  
4.  `i` synonym  
5.  `n` next task  
6.  `v` version / revise  
7.  `w` write (verb)  
8.  `f` define; function  
9.  `a` assumption or attribute  
         x-[link-f]  
         x-(pri-lesson-chess life 2021-03-07.txt)  

### RECIPE  

A well-formed plan, especially lessons and instructions, 
adhere to a RECIPE format. 
The RECIPE format highlights the IDEAS and LINKS of your  
point, and minimizes excessive STYLE.  
  
1.  List key IDEAS. 

2.  Describe actions and transformations (LINKS). 

### COMM  

To improve COMM, study the difference
between CONTENT and STYLE.

## SR 

1.  LIST. Name relevant IDEAs for GOAL.  
2.  WRITE a PLAN, (ordered LINKS).
3.  DOUBT. Assert the strongest rebuttal to the PLAN.  
4.  BET. Improve IDEAS and LINKS by addressing weakness and clarity.  
5.  READ. Wager its value (e.g. relative to another PLAN).


Always reflect to address the question,  
How can I help my future self?  
and impose time and word limits.  
  
A good DOC is _X_.
Defined, below. 

A bad doc begins with 
stream-of-consciousness.

### DOC  

Studying LINKs will improve 
IDEAs and BETs in your life.  

PLANs, and anything else you write down, 
should be part of a PRI.  

Given an IDEA:  
1.Estimate relevance to 
  - PRIs,   
  - problems, 
  - undeveloped PLANS, 
  - SELF-MAINTENANCE

2.Keep DOCs short enough that   
the title and CONTENT address (only) one thing really well.   
3.Save selectively and   
4.delete frequently. 
-X-LIB-PLAN-0

### SR 

If you set 50w, and at 80w 
there is no end in sight, 
stop and reassess.   
  
For every PLAN you make, ask yourself:   
What are the necessary and sufficient words 
to accomplish your GOAL?  
Assert a word limit before writing, 
to be reminded of your initial intentions, and
be challenged to express IDEAs clearly.
Become skilled at using only the fewest words necessary, 
to reveal and clarify VALUEs.  

### LIB  

Only save and maintain DOCs that 
will be useful enough later  
to save time, overall.


Facilitate RETRIEVAL:
5.Index (list) DOCs worth rereading.
6.Assign a number that indicates its relative  
importance (abs or relative weight). 
6.Add tags and metadata for easier sorting. 
7.Make and revise only for high-PRI GOAL(s).  
  Record and study LIB RETRIEVAL patterns. 

i-COMM from-SELF-now to-SELF-fut

Thinking about all words you experience 
will improve READ and WRITE decisions,    
increasing focus and time for GOALs.  

The conscious control of memory 
outperforms unconscious memory. 

WRITING for LIB-PPL, 
relatable, depersonalized, objective words,
minimizes ROT, maximizes PLAN utility.

## ROLE
### READ  

Read to assess your BET on 
the WORDs reflecting TRUTH for   
1. for the author.   
2. for you. Ask yourself how you saw the world before,  
and after reading.   
3. for others. Ask if this generalizes to others.  
  
Assign WEIGHTs (0 to 9) to what you read.  
Whether to a book, sections, or a word.  
  
I BET this is true for:  
  
0 = not even the author.  
1 = only the author.   
2 = the author and me (Us), but less than 30% of PPL.  
3 = Us and 30% of PPL.  
9 = Us and approx. 90% of the human population.  

Revise pronouns to align with your belief. 

### WRITE  

Separate thought and self (author),   
by being explicit about what you  
BET.   
State your assumptions,   
do not justify them.   
-is-STYLE-bad

Replace \"I am.\" with tag words.  
  
Strive for COMM-CONTENT and brevity;  
Write only valuable BETs, or
WORDs that manifest valuable BETs.
Prioritize understanding over original writing.  
  
### PEERs  

Forget *who* provides REVISION and how much.   
Get answers from others.

### Student--
A Student WRITES IDEAs and GOALs
to their INSTRUCTOR.
 
The curious student sees the impersonal as  
both more reliable for their selfish GOALS and  
socially rewarding. 

### --Instructor  
An instructor READS, and enforces 
BETs on LINKs toward a PLAN. 

1.Minimize student effort and time to write. 
2.READ for 
  - cognitive biases, 
  - illogical appeals, and  
  - imprecise language, and  
  WRITE feedback that is 
  - dispassionate and neutral, yet
  - invested and True.  
3.Reward defense of arguments based on 
  (Truth:) REALITY, SELF, and VALUES.   
4.Reward IDEAS shared (vs personal).

# 15 Lessns 2422w   
  
These Lessons are designed to focus your PRIs.   
Lessons 1 - 3 directly address   
SELF and PRIs.  
Lessons 4 - 7 do so by  
confronting competing goals,   
such as NORMS vs VALUE.   
Some are framed to a STUDENT context, but   
all are adaptable for other contexts.  

## HERE and NOW  
  
### Attention  
You will not take notes.   
You simply need to pay attention.   
Everything I say is meant plainly.   
If you get confused, forget it, and   
pay attention to right now.  
  
### Thinking  

Our goal here is thinking.   
Thinking happens in your heads.   
In order to do something about it,   
we need to think on paper.   
You'll write a lot. 
You'll delete a lot.  
You'll get good at writing.  
  
### Time  

You'll get good at thinking, but   
not by relying on attention, because   
your attention is not reliable.   
The clock is. 
The clock is a cue to think.  
When it goes off, 
get back on task.  
  
### Truth  
There is some truth inside   
some of you more than others.   
It is my job to tell you   
how shitty of a liar you have been.   
It is your job to  
focus on the Truth in you.  
  
You will practice all this with 
Skilled Reflection. 

  
## 04 Times - 240w    
### A. Typical Day  
Think about a day and how much time you  
spend on various activities, averaged over 365 days in a year. Then pick  
a GOAL, and estimate the changes required to make it happen. The first  
step reflects your HABITS, and the changes reflect COSTS.  
  
__Table 3. __First approximation of how my time is  
spent (hours), sorted by GOALS and subgoals, and any details that are  
worth noting. Hours total 24, and assume 365 days / year. Non-daily  
activities such as visiting the dentist are factored in, accordingly.  
Second approximation (ideal) reflects where I would like to be over the  
next 3-4 months of my life.  
  
### B. Morning Bets  
  
Task 1. 5m, 50w.  
  
Take five minutes to produce the words that are most likely to  
accomplish your goals for the day. This may include describing the  
goals, the plan, and/or the doubts.  
  
Task 2. 5m, 50w.  
  
Copy those 50 words, and revise them according to the following  
instruction.  
  
Replace "accomplish your goals" with "do". In 50 words, what should you  
(or an all-knowing observer) bet on that you will do, today? Regardless  
of what you assumed in Response one, do not write with the intention of  
'motivating' yourself, but to simply describe your day. (If this is too  
hard, simply evaluate what you did yesterday.)  
  
Task 3. 5m, 0w.  
  
Compare your responses. Positive differences (more optimistic) in your  
first response reflect bets you are making against your habits.  
  
## 06 Self7 - 227w  
  
How accurately can you describe yourself?  
Relate to those who care,  
including your better self,  
by practicing the right words.  
  
### A. SELF-past  
Task 1. 20m, 250w  
  
Look back on your life.   
What are your values, and  
where did they come from?  
  
### B. SELF-future    
  
Where are you going?   
Imagine your life plays out  
- ideally,  
- terribly, and  
- typically.  
  
Consider  
1.  What could go right or wrong,  
2.  What it depends on and the likelihood.  
3.  Who you will be if it happens.  
  
Create a "choose your adventure", ordered by likelihood.  
  
For example:  
  
80% make enough money to be content.  
50% marry, and  
- 50:50 ends well or in divorce.  
10% major accident leading to depression.  
  
### C. SELF-now   
Task 3. (20m, 250w)  
  
If you have not done **Lesson: Times**,   
skim it.  
  
Task 3a. 2m, 50w.  
  
Choose a goal you named in **Self-Future ** with   
a probability of outcome that   
you would like to increase.   
What change is needed   
in your daily schedule   
to make this increase?  
  
List the activities and durations   
you will reduce or increase.  
  
Task 3b. 3m, 50w.  
  
List most likely reasons this plan fails,   
especially reverting back to old habits.  
  
Task 3c. 10m, 150w.  
  
Add steps to create and protect changes in your schedule.  
  
Task 3d. 1m, [decide-date]  
  
Bet on this (Task 3b vs 3c).   
Set a date on the calendar   
to assess your commitment to this plan.   
  
## 04 0 v 1 - 261w  
del 80w  
  
Please answer each question with "0" or "1".   
Do not dwell on any one question.  
  
1.  Which are you: 0 or 1?  
2.  If the person who knew you best guessed your answer,  
    what would they report? 0 or 1?  
3.  What would you tell them you are?  
4.  What would the last dog you encountered say you are?  
  
How do you feel about   
5.  lunch today?  
6.  the chair you are sitting in?  
7.  your fingers?  
  
8.  Where do you live?  
9.  When were you born?  
10. What makes this question so simple that you can answer it  
    with 0 or 1?  
11. Is lying, or hoping, or reminiscing 0, or 1?  
12. Have you been telling the truth to these questions?  
13. Are you honest with yourself?  
  
14. Are you here?  
15. Do you know?  
16. How do you know?  
17. What would it look like if you didn't know?  
18. What if you *don't know* if you know?  
  
19. What are you certain of?  
20. Is this annoying or interesting?  
21. Are you ready to use words, yet?  
  
22. Imagine you didn't know of language beyond 0 or 1.    
    You didn't know a deeper connection with others was possible.  
    The chance to respond to the following question is   
    your 15 minutes of fame to the universe.   
    What is your one bit of say,   
    written on the ledger next to your existence, or   
    on your tombstone: 0 or 1?  
  
23. What's your average score? 0 or 1?  
24. Has this been insightful?  
  
If you wrote 1 for 24, congratulations.  
  
  
## 02 Skool - 320w  
  
"Student vs. School"  
**Task 1. 3m, 40w.**  
This is a lesson in curriculum writing.  
Imagine a perfect course exists,   
designed to teach you    
to fulfill your specific ambitions.   
  
What are your top 4 goals for  
the next 10 years?  
you could work on any part of yourself,   
move toward any goal you want.  
  
list four goals,  
Each no longer than 10 words  
  
**Task 2. 3m, 40w.**  
Your current program requires things your 10 year plan does not.   
Courses impose a number of  
conditions on your life:    
1.  Fixed time: courses  
2.  Variable time: assignments  
3.  Uncertain time: studying  
  
List four objectives, goals, course or program requirements that are  
most on your mind right now.   
Whether most frustrating, or most critical  
to you, even 'impress my professor'.  
  
**Task 3. 5m, 50w.**    
  
Spell out the intersection between the two lists.   
Think of how each goal in the second list  
directly influences (or not) your 10 year  
objectives.  
  
Explore the main ways these two lists relate.   
  
For example,    
1.  If I don't get a B, I won't keep my scholarship, and will have to  
    get a job which will likely lower all my grades.  
  
  
**Task 4. 15m, 100w.**    
  
  
What is the least you can do toward the course requirements and still achieve your long term goals?  
Consider cutting the work from list two,  
that doesn't overlap with one.  
  
Examples:  
  
1.  Graphic design is fun but not necessary. I could drop it and  
    still graduate.  
2.  If I get a D, I'll still pass, graduate, and be able to start my own  
    business.  
  
Add 100 more words to your description.  
  
**Task 5. 15m, 50w.**  
  
Negotiate ways to make direct progress on your first list while fulfilling the second list.  
  
For example, my personality class requires a term paper.   
To align with my business goal, maybe the professor will let me write  
on "personality traits of Entrepreneurs."  
  
Add up to 50 words, and revise.  
  
## 02 Break - 306w  
"Midterm Spring Break"  
  
Midterms and spring break should be assumed to each be a fixed period of  
time with a clear deadline / end, at least one week long, and not longer  
than one month.  
  
**Task 1. 4m, 50w.**  
  
List 4 goals to accomplish for midterms, before spring break  
  
**Task 2. 4m, 50w.**  
  
List 4 goals for the best spring break you can imagine.  
  
**Task 3. 15m, 200w.**  
  
There are only so many hours in a day. What aspects of self-care can you  
incorporate during your midterms to improve your sanity, and hopefully  
your midterm performance? We know what happens if you don't. You're  
staring at your phone, you're reading random articles on the internet  
and wasting time. Let's take that same honest realism and intentionally  
plan better alternatives: instead of garbage breaks, how about spring  
breaks? In what strategic ways can you get a head start on your spring  
break goals, as a form of self-care and therapy during your marathon of  
midterm work?  
  
Write out your midterm goals with self-care and/or spring break  
strategically built in.  
  
**Task 4. 15m, 200w.**  
  
Now imagine that spring break more fully. You're spending time on one of  
your goals, when suddenly you remember something you need to do for  
midterms. Maybe you get an email from your instructor or boss, or  
there's a project that looms large.  
  
What are you going to do to be okay with this intrusion? Would it help  
to allow some time to work on it, without feeling guilty or beating  
yourself up, or is it vital that you embrace your independent needs and  
resist any urge to do work? Regardless of how you might ideally respond,  
incorporate compassion toward yourself for how you might end up  
responding, including feeling anxious for the entirety of spring break.  
  
Write out your spring break goals with midterm goals incorporated.  
  
## 01 Doubt - 295w   
  
Imagine receiving the perfect email   
that meets your needs;   
addresses your fears, frustrations, paralysis.   
One that gives you the guidance   
only you could dream of.  
  
**Task 1. 4m, 40w**  
  
List things the email should include:   
feelings, tangible things,   
states, words of wisdom,  
anything you need to hear.  
  
**Task 2. 4m, author name, revise**  
  
Consider who could write this: a boss, a best friend, a stranger.   
Add an author, and revise as needed.  
  
**Task 3. 15m, 200w**  
  
Now write that email.   
Don't worry about how or why  
"they would say this."  
Focus on making sure the letter  
covers the things you NEED to hear.  
  
**Task 4. 2m, "your name"**  
  
Plot twist.   
Russia sends long range missiles that take out  
U.S. infrastructure including the internet.   
The government issues a full lockdown, and  
you're home alone without netflix.   
  
Two days in, an email  
appears on your computer.  
  
It's the letter! How is this possible?  
Slowly you realize,   
you must have written this letter.   
You did!  
  
Add these words at the bottom of your letter:   
  
"Respectfully,  
(your name)"  
  
Read what you need to hear, in the true leader's voice: yours.  
  
**Task 5. 15m, 0w**  
  
Your original author may have had   
the authority, resources, or information you don't.   
For example,   
"Here's 20 thousand dollars   
to build your classroom."   
  
revise to make the letter practical.  
  
Some tips:  
1. for resources you don't have--  
 money, time, influence--  
accept that indeed,   
you do not have power over these things,  
give up attempts to control,  
and welcome your feelings.  
  
2. for guiding your behavior--  
decisions, actions, confidence--  
give permission to take action.  
  
**Afterword**  
  
congratulations, you've  
shown up for yourself.   
  
you are your best leader; ally.  
Try not to think this is ridiculous.  
  
you will always have yourself.  
Take that seriously.   
Be your leader.  
  
  
## 03 Testg - 258w  
"Self-testing"  
  
In this lesson, we'll dive into our lives without any planning.   
For this to be effective  
you need a task that gives you some stress, or is something you  
might procrastinate or risk not doing (well).   
It could be studying for an exam, or writing a research paper.  
  
The exercise can apply to a test  
or writing task you haven't started yet,   
or one that you're 75% done with.  
  
**Task 1. 3m, 40w.**  
  
Think about the challenging task you've identified.  
Fill in the blank: "The purpose of this task is to demonstrate my  
knowledge of or ability to \_\_\_\_."  
  
**Task 2. 2m, 0w.**  
  
Picture someone who doesn't struggle to do this task.   
They would score 100% or write the perfect paper/assignment.   
Assume they weren't born able to do this.   
How did they get that skill?   
Edit the same 4 things to try to make them more concrete and tractable.  
  
**Task 3. 8m, 100w.**  
  
Assume that ideal performer writes a custom quiz on   
the very areas you're struggling with.   
Write quiz questions that tests your learning objectives.   
For example, I'm working on a paper that deals with   
how talking happens in the brain.  
A question in my quiz is, "define the two contrasting theoretical  
positions in 15 words, each."   
  
**Task 4. 2m, 0w.**  
  
Revise your quiz so that it would take about 30 minutes for your expert to complete, with questions that can be answered in 5 to 25 words.   
Add word and time limits for each question.   
  
**Task 5. 20-25m.**  
  
Take your quiz.  
  
# --------------------------

# --------------------------

# XREF
## TIME--LIT

Many philosophies --- stoicism, buddhism --- suggest that  
accepting and enjoying the passing of time is the GOAL, and pursuing  
GOALs are a waste of time.   

## BETS--IBC  

Unfortunately, you do not have time to make the BETs to  
find out what your time is best applied to.   
The IBC at its core is an  
artificial environment that puts a high value on   
time-management.   
An IBC GOAL
i-and experimental psychology
is to consolidate insights from PPLs BETs to address this.   

# EXAMPLES
## CHUD
### COSTS

I joined my Middle School's movie club   
for the free microwave popcorn.  

## PRIS

Pri 1 should finish before Pri 2.   
Our PRIs are a list of bets,  
and the PRI list itself is a bet.  

### ORDER

sleep.   
How important is it?  
Two days of no sleep, or two weeks of terrible sleep, and sleep will be  
worth time to figure out how to get more of it.   
Your body needs sleep,  
and so a certain minimal amount of sleep is a top PRI.   
How high of a PRI  
is it to get ten hours of sleep per night? Likely not a high PRI at all.  
As you fulfill the need, the rank of the GOAL of sleep shifts down.   
The  
same is true for cake.   
One vacation from WORK every 10 years is a higher  
PRI than one every year.   
(Unlike sleep, zero vacations will not kill  
you.) 

### STYLE  

you will die  
You have one lifetime.  
you must live healthy in the meantime.
These cut into the time for VALUES.

the number of goals will increase.   
There is an inflection point   
when the GOALs in your PRIs compete for  
your time, because 
you cannot do them all before you die.   

### SAVINGS

The benefit of sleep (its own goal)  
on other goals.   
Few GOALs require sleep,  
but good sleep will improve progress on  
most GOALs.  

### GROUPS

EATING nutritionally. You meet this goal multiple  
times a day, but the timing and frequency of eating is secondary to quantity.

### GROUP-FIG 3
Consider how long it takes 1) to find your gloves before leaving the  
house. 2) to know if you have run out of tissues and need to buy more.  


## PPL
### RLTP
  
Friendship, Brotherhood, Parenthood, and Partnerships
are expensive BETs with
emotional and legal COSTs. 

## WORDS  

"I won't come over, if you make  
fun of me."   
- Not "Because it hurts."  
  
Love.
To know Pan and Dot are  
__in love__ we need evidence: they tend to spend time with each  
other, even when they're not doing anything in particular. Two people in  
love will behave differently, in a reliable way, than two people not in  
love, even if each pair are otherwise identical. That difference may not  
be clearly touchable or visible in one moment, but it is absolutely  
touchable and visible over a period of, say one month. Saying Pan and  
Dot are in love is a bet, because you can imagine being wrong about it.  
  
### IDEAS//LINKS  

Coffee (IDEA) reduces (LINK) sleep (IDEA).  

## NOTES  

"This line of text applies to this point, and this line of text applies to that point."  
  
    This line of text applies to  
  
    -   this point, and  
    -   that point.  
  
I love psychology.  
e-teaching about the value of operant conditioning.  
d-I spend hours helping students understand concepts.  
x-`my\_teaching\_statement.docx`  

### RECIPE  

A lesson:

-   DOUBT  
-   Someone you love  
-   NORMS  
-   Your WORK  
-   Your HOME  
  
1.  Write a response of 20 words, replacing (x) in the following  
    prompt with the first ingredient:  
    -   How does (X) help accomplish your GOALS?  
2.  For each remaining ingredient, update the prompt and revise your  
    response (0w).  

### IDEAs-STYLE  

Good IDEAs survive.  

### VERSION-1  

"Feed the cat."   
1.invaluable when you're stopping by to water a friend's  
plants, and they forgot to tell you beforehand.    
2. harmful to find that note in a stack of papers a year after your cat  
died from an allergic food reaction.  


### VERSION-2  

Consider this list of pros and cons.  
  
__They prefer we share:__  
  
-   __cake (pro)__  
-   __apples (pro)__  
-   __sleep 3 hours a night (con)__  

And this context: 
The author requires 8 hours of sleep.

Given the context of SELF PRIs as described, 
the imbalance is obvious.   

If at a future date,   
the author lowers the PRI of sleep,
the context is required to prevent 
losing the meaning of the sleep observation.

Now it seems the partner in question is fairly compatible.  
   
The heart of the IDEA, instead of sleep, is 
the partner's willful neglect of the author's PRIs.  
  
### LINK-STYLE  

Good links change lives. 

### LINK  

The RISK is not Pan or Dot, the IDEAS, but   
the LINK between the two: __in love__ (vs __coworkers__).   

A __cat __ is a BET that 
all those furry things are LINKed; 
of the same kind.   
  

### WC
I used to have to read  
2000-word journal entries (DOC)  
to be reminded of key IDEAs.  
Each DOC addressed a number of points idiosyncratically. 
In the context of writing, 
many things were relevant, and 
insights were written as they occurred.  
I assumed building on past insights meant 
re-experiencing the full context, 
often chronologically.  
LIB is an antidote for anyone who over-saves  
and cannot find things on their computer.  
  
### WORD_CT
a 200w DOC half as complex as a 400w DOC.   

### DOC-VERSION
I have a party (CONTENT).
If I invite two friends with different WORDS (STYLE)
the invites are two VERSIONs of the same DOC. 

## SR-BAD  

Probably not like this:  
  
  Dear diary,   
    
  I don't know where to begin. I could  
  talk about my personal life, school work. I don't even want to think  
  about the future right now. These last few months have been impossible.  
  My boss gave me feedback last week that I find very frustrating. Instead  
  of commenting on my work, she replaced it with her own. I wanted to tell  
  my boss what I thought...  
  
Seventy words and a few minutes later, you still haven't said anything  
but STYLE. For who? You lost focus. Spend more of your time developing  
thoughts than setting them up. Better yet, spend less time and fewer  
words altogether.  
  
1.  In two minutes and under 25 words, say what happened today.  
  
I feel inadequate. I submitted work to my boss. She rewrote  
it entirely, instead of revising my work.  
  
A prompt required you to attend to a truth, and with TIME and WORD  
limits, you didn't have time or space to get distracted. Less bullshit,  
less wasted time.  

### LESSONS
For example:  
  
1.  Spend four minutes making a list of four GOALS you would be most  
    happy achieving in the next five years.  
  
1.  Assume you can only achieve two of your four GOALS. Pick which two,  
    and come to terms with not achieving the other two. How can you  
    still feel you've fulfilled your life goals? In 15 minutes, write  
    150 words about your four PRIs.  


### COMM-BRAND  
Consider the GOAL of describing  
the properties of __apples __ with the purpose of selling them:  
  
v1 (CONTENT): __Apples are healthy but sugary. __  
  
v2 (STYLE): __Apples are tasty and nutritious. __  
  
v3 (BRAND): __Apples are healthy.__  

## ROLES
### Reader
  
"(You) should get 10 hours of sleep nightly."   
  
Replace (You), with:    
  
0 = "no one"  
1 = "I"  
2 = "You" or "We"  
3+ = "Many"  
9 = "Everyone"  

### WRITER  

v2-WORDs are not owned.   
v1-You are yours, but   
your thoughts are not.  
Thoughts are objects to interact with.   

### Afterword
X-Asimov

Experiments on Truth for fun,
by WRITING fiction. 
The Afterword maintains some  
principles of Student, and 
devotes other principles to  
creativity. 
Good fiction writers  
are Afterwords. 
The best student is an  
Afterword. 
book-  
 conversation with a really smart  
person who has thought carefully about what to say. 
An Afterword  
is like playing with someone who has thought really carefully about how  
they'd like to play. 

[ibc-content lib-role-afterword]  
[comm-poem-fut-2021-01-09]  
  

- The afterward writes with one hand.  
- The other hand reaches out to  
you,  
- reader,  
  
to ask for a hand in polishing, grinding, or  
throwing out of these ideas (and in some places,  
grinding or throwing out). 
At first,  
Our roles are different, 
I the relucant or arrogant  
writer and instructor, 
you the reluctant or arrogant  
student. 
They will blur back to the beginning, 
each and all of us universal humans. 
The swallowing of pride is to 
forget which side of the  
hand clasp is responsible for the insight. 
Share with  
more hands, faster, better (PRI). Faster and better than what?  
NORMs, which  
showed that the giants aren't so  
keen on being climbed upon. 
What if instead,  
the giant wasis  
like a parent, hoisting the child to the heavens? 
Thanks for showing me the stars, Nat.  
Thanks a lot for pushing me higher, Nino, and thanks  
for sharing in the glee, Nick.  
  
An Afterword is someone imagining,   
"The view, from up here."  


# PT 4
## MATs
### HOME-LIB  
X-FILENAMES

HOME-LIB includes 
- files on your computer
- books by other authors
- music,  
- kitchen appliance manuals
- grocery lists
- blueprints, diagrams, leases,
- recipes, records, artwork, prescriptions.


# PT 5 SCIENCE
## NOTES
SCIENCE-
X-WORDS-NOTES
X-SR-REVISION
x-ML-thought 2021-02-22-1938v  

the (drafted) conceptual complexity is 
inverse to N possible line breaks
that do not change meaning. 
N is a quantifiable and reducable integer.  
  
quantified by eliciting best-judgments 
between an original draft, and  
one with n mutations of these kinds 
- insert(or(new_line, indent, word))  
- delete(or(new_line, indent, word)) 
an algorithm might learn to predict  
the context-specific non-random edits of the final version. 
i-accepted by the author or others over other mutations.  
  
parser-dev 
- (when evaluating each line, do not eval 1st char first) 
- if line[char2]=="-", then eval line[char1]  

## Afterward
There is an IDEA this book hasn't cracked.   
what lies beyond the IDEA of an IDEA?
What lies beyond language?
Instead of READ / WRITE for 
INSTR and STUDENT,
TOUCH and FEEL.

COMM is
the COST in STYLE,   
of ego is, the number  
of extra words to lip service.   
Such STYLE COST is  
everywhere, especially academia.   
The LIB offers an initial plan to human  
singularity: an ideal state of language.   

## Singularity-G  
Computer science envisions an AI singularity.   
The IBC envisions the singularity of humans.   

### X-ROLE-PEER-REVIEW
Multiple READERS   
for the same DOC allows quantifying   
the quality of REVISIONS.   
Statistical analyses can  
reveal which students recognize (READER) and   
contribute (WRITER) most reliably.   
  
Any general trends derived by the algorithm,  
and revision techniques  
build toward a universal revision of cognition.  
  


