# BASIC
to understand what a garden is,
inside out,
you must go to the clock core.

What follows is INSTR for clock-makers

## SELF.R

LIB(DEFS.xlsx)

SET TIME IF YYYY-MM-DD-HHMMSS
  CT TD

INIT (PRI < SELF < PPL < WORD)
  WITH GOAL (PPL < SELF < 0 < 0) 

SELF FOR (HOME, WORK, ED)


## DOT's PHENOMENAL-DATA POINT 

Begin with the UNKNOWN (I-DESCARTE)
LET a MOMENT be IRL PLACEMENT in TIME and LOCATION (SPACE).
NOW, you are a SELF, a 0d (DOT) CONTINUING in TIME from BIRTH UNTIL DEATH. (SELF.NOW = CT(SELF.BIRTH -- SELF.DEATH))
IF SELF.DATA is KNOWN, a DOT represents the exact physical center of you on a map of the planet, NOW. IF we LINK every DOT of you from BIRTH to DEATH, we have an exact a line tracing the complete and true existence. 
in HD, DOT can be any physical POINT on the body.
Thus, the ACT to STAND, SIT, SLEEP are the derivative changes in DOT position as a function of distance from the planet's center.
That which LIVES is anything whose DOT exhibits !GRAVITY.
No rock climbs a hill, but moss does. Sand goes one way, but a plant another. Eventually all return to gravity.
WONDER what causes patterns of !GRAVITY?
This is PHENOMENAL SCIENCE.

## ALL non-BASIC IRL DOT-CHANGE is WORD. NOT ALL WORD is IRL.
WHAT can be NAMED which derives any change in POINT is IRL when the predictor is PLACE*TIME, else WORD (MIND*ATTN) for anything else.
never MIND ATTN for now, WORD is what is called that causes ALL other changes in DOT. 

A



