
# Introduction

Dear me, 

## Dear
1.	Read this book because you're ready to.
2.	You are going to die someday. This book is for you if there is something in the 
meantime worth maximizing.
3.	Please engage your life. 
This book is meant to help you understand and take action, starting right now.

## Test
4.	Please get a pencil and note the date and TIME, right now: ____________. 
5.	The WORDS in this book are meaningful only when you apply them to your life.
6.	If you wrote the date and time as requested in step 4, you have proven enough to yourself that you are open to trying 
new ideas. You are prepared to grow and continue reading.
7.	If you left the line blank, you might tell yourself you are open to new ideas. You 
will be right when you complete the task. 
8.	Either write the TIME above or stop reading, and take a better action to improve 
your life, right now.

## Game
9.	From now on, every WORD you (or I) say is a PLAN for action.
10. That PLAN is meaningless until you take that action, whether GOOD or BAD. 
11.	Therefore, spend less time worrying about why this WORD or that PLAN.
12. Spend more time deciding which will be the next moves in your game of life. 

13. Sincerely, student0


## Camp  

13.	This book presents plain and obvious facts of life as the antidote to modern complexities of life.
14.	In  most cases, the relevance can be seen more clearly if you [simulate][WORDS] the experience being described, or explicitly consider it in your life (See [Role of Reading][READ]). Let's practice. For example, consider going on a camping trip. 
    1. Look at the clock and determine when you should expect to arrive. 
    2. Whatever that time, when you arrive, you will likely be over- prepared, under-prepared, or 1-3 hours late.
    3. Or you might be an experienced camper.
15. Either way, this is your only shot at a lifelong camping trip for yourself on Earth. 
16. My guess is you are very likely late to your own life. 
17. The games we (PPL, SCIENTISTs, etc.) play to explain away this fact, end with this book.

## Pitch
18.	To understand this book will require you to find and repair the disconnect between your mind's image of TIME, and the one you are physically bound to. 
19.	If you fail, you will die in two worlds, the world you imagine you could have 
lived, and the one you did. 

20. You, however, would like to ace your own life.
21. Part one of this book (The Garden) gives you all the general answers, and the basic tools for finding the answers particular to you.
22. Part two teaches you how to (re)build your tools.

## Eat
23. The one thing up to you that this book will not do is draw the line between need and want.
22.	In this book, FOOD refers to needs and CAKE refers to wants.
23. You must practice discerning which is which for you, until it is second-nature.
24. Then, all decisions can be made as follows: 
    1. If hungry, eat FOOD.
    2. If full, prepare and pack FOOD.
    3. If time, eat or prepare CAKE.
25. Beware of thinking CAKE is FOOD.

## Homeless  

26. Do, don't think. Likely at this point you have slipped into thinking this is a book discussing a philosophy, but it is not. 
27. FOOD vs CAKE is not understood and solved as a mental exercise in your living room, but by experiencing and paying attention. 
28. What's more, if you don't have a living room, CAKE can be painfully obvious. Be homeless.

## Food
29.	The odds are you aren't homeless and will avoid becoming so.
30. As with any hypothetical, practice finding the nearest analogous, personally meaningful experience: 
    1. You couldn't find your car in the middle of winter. 
    2. You went camping without waterproof gear and it rained. 
    3. For weeks your shower only produced ice cold water.
    4. You were isolated in your house for most of two years during a global pandemic. 

31.	Whatever the circumstance, your HABIT protests for a change in PLANS.
32.	However small or profound the suffering or its threat:
33. There is initially terror, frustration and suffering. 
34. Enduring, suffering will change.
35. You will need far less FOOD than you thought, giving more time and quality CAKE you really desire.


## Plan
36.	In the first half of this book is a conceptual metaphor described as a Garden. 
37.	It is a mental model of reality, designed to bring clarity. 
38.	Your Garden is your GOALS put on key IDEAS of this book.
39.	You need the Garden to combat the idealistic side of your mind, inclined to ignore TIME and your SELF, which sets you up for failure and suffering.
40.	The second half of these chapters elaborates explicitly on the key IDEAs.

## LESSONs
41. At the end of the book are a series of [LESSONs][Zero or One] for identifying what matters, what's wrong, and what's next in your life.
42. They are designed to be useful at any time, and especially repeatedly.
43. Don't wait to finish the book to try one out, because they are pivotal to Skilled Reflection.
44. However, don't do too many of them before at least reading the relevant section that explains the format of [Skilled Reflection][Skilled Reflection].

## Definitions  

45.	WORDS in all capital letters are IDEAS that have specific definitions that differ 
slightly from conventional use. 
46.	For example, "WORK" is an IDEA referring to "careers", but not 'yard WORK'. 
47.	Do not overlook the nuances for these terms, they are the result of careful decisions about the FOOD and CAKE of the IDEAs.
48. You can find a list of the key ideas in the [Index of Definitions][Index of Definitions]. 

49.	<- Use the enumeration of ideas to cross-reference.
50. The item immediately above is "c1.49". "c1" referring to the chapter "Introduction", and "49" to the numbered IDEA.
51.	This system will be taken advantage of in future revisions.
52. Each chapter deals with a distinct perspective or dimension of life and the GOALs related to it. What is said is what can be simplified for generalizable guidance. 
53. Like FOOD vs CAKE, the HABITs relevant to your GOALs can be closer to FOOD, or excessive like CAKE.
54. In the context of definitions, they will be referred to instead, as "good" and "bad" (For example, [c9.60][PRIs Differ]).
