---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

# (PART) The Garden {-}
# SELF

## Your Garden

1.	Imagine your life takes place in a garden.
2.	Visualizing your life as a garden allows you to ground actions and PLANS. 
3.	The mind analyzes well with visual space. 
4.	In this garden we'll consider all your biological needs -- eating, sleeping especially -- as literal. 
5.	Your plants are GOALS, and gardening is your PLAN. 
6.	FOOD and CAKE exists in the form of fruit from plants.
7.	Whatever it takes to obtain your CAKE you can consider as an act of gardening. 
8.	Every one of your life ambitions, GOALS, is buried in the ground as seeds. 
9.	Finding a life partner, acquiring a car or promotion, or resolving a conflict with 
your childhood friend are all matters spread across the dirt in need of water, 
sunlight, and--most important--your TIME.
10.	Other GOALS, like your favorite hobbies, or TV shows, take little WORK and 
grow almost anywhere. 
11.	Whether they are dear to you or weeds, if they take your TIME, they are PLANTS 
in your garden.
12.	Except that they start as seeds. 
13.	And what do you do with seeds to make plants? You garden, dear human, you 
garden.
14.	All actions toward a plant are according to PLAN. 
15.	All actions toward your SELF are to be considered literal in the garden 
metaphor.
16.	For example, if you need to eat, or go to the bathroom, you physically go to the 
place and literally do the deed. 
17.	(There will be no pooping on plants, or a pooping plant in this garden.)
18.	Thus, in the garden you are still a normal human bound to a normal space and 
time, capable of: 
18.1.	acting according to bodily need, 
18.2.	moving about space, and 
18.3.	gardening.
Today
19.	Today, you are looking out across the entire garden. 
20.	What has already been planted? What will you add and how much TIME will you 
devote to those GOALS? 
21.	Every seed you plant -- even an abstract one like passing a course or making a 
friend-- implies things in and out of your control like WORK and weather, or 
beyond your awareness, like what your boss loses sleep over.
22.	Meditate on the final products of your garden. 
23.	Is there a more important plant that deserves your TIME today?
24.	Meditate on the priorities of your WORK. Do two plants grow better when 
together?
25.	Make a quick and accurate assessment, but don't sit here all morning thinking 
about it. 
26.	A garden is for working in, to get the FOOD and CAKE you need. 
27.	What do you need to cultivate, today? 
28.	What do you want to cultivate in this life?

29.	First, you want what your body and mind best respond to. Many of these seeds 
will be obvious. 
30.	It is up to you how curious you are for what better life is possible.
31.	The day is too short to try everything, and many things are not worth trying. 
32.	There is not always harm to planting something that does not grow, but 
sometimes there is. 
33.	You could run out of space, TIME, or energy that could have been devoted to 
better crops; 
34.	You might get a weak yield for trying to grow something not suitable in your 
climate, or 
35.	find you have no taste or stomach for the fruit.
36.	In the garden, the COSTS of GOALS are grounded in their most basic sense: TIME 
and attention.

## Core Concepts

37.	The following are core concepts for application beyond the Garden.

GOALS
38.	A GOAL names an ideal future reality, comprises a PLAN to increase its 
likelihood, associated with CHUD.
39.	These three things encompass all cognitive activity related to reality.

40.	Call anything that could be true, but isn't right now, a GOAL, and any effort in support of making it true a PLAN. 
41.	It is *your* GOAL if you aim to increase its probability of being true.
42.	A GOAL can be finite or persistent, singular or recurring, or realistic or not.

43.	If you will need to do something before it is in your hand, it requires a PLAN.
44.	A PLAN is any combination of WORDS where the writing or reading of them aims 
to improve the chance or decrease the COST of achieving your GOAL.
45.	Most PLANS are instructions (INSTR) for learning, making, changing, reminding. 
45.1.	Product INSTR are a PLAN to maximize satisfaction and minimize liability. 
45.2.	For example, lamp INSTR will likely suggest not to put it in water. 
46.	A DOC is a PLAN for GOALS to complete a linguistic product
46.1.	Example DOCs include a resume or epitaph on a tombstone.
47.	LESSONS are a PLAN template for thinking. 
47.1.	Read and complete LESSON steps in order.
48.	TOOLS are physical or mental objects that help you accomplish your GOAL.

49.	What is materially required--muscle energy, cash, brain power--is COST.
50.	All COSTS can be reduced to TIME.
51.	COST is any action that has a direct exchange.
52.	COSTS often are secondary objectives within a PLAN.
53.	For example, you might buy a TOOL (COST). 

### SELF  

54.	Every day, as a human, you spend TIME and attention just meeting basic needs: 
eating, drinking, pooping, and sleeping.
55.	These actions are subgoals of maintaining SELF, the category of basic human GOALS.
56.	FOOD is the necessary and sufficient material to satisfy these needs.
57.	CAKE is anything (else) fulfilling, that you are inclined to pursue, including the reason for living.
58.	The GOALS of SELF are what's necessary and sufficient to obtain and manage FOOD and maximize BET outcomes ([c5.28][BET]).
58.1.	Separate FOOD from CAKE. 
58.2.	Be careful not to mislabel CAKE as FOOD. CAKE may appear sufficient but 
ask yourself if it is necessary. 
58.3.	Build routines for health and fitness, physical safety (shelter), a sound 
mind, healthy relationships.
58.4.	 Master the SELF (survive well).

### Home  

59.	HOME is the collection of materials and TOOLS needed for SELF.
60.	Within a HOME related actions are grouped into rooms. 
61.	For example, a kitchen, is for eating, storing, preparing and disposing of FOOD.
62.	HOME also includes all physical material and resources you own, including 
MONEY, and environment and basis for HABITS.
63.	A good HOME is clean and ALIGNED for FOOD. 
64.	A bad HOME facilitates bad HABITS and takes more TIME to maintain.

65. All your life can be very well characterized by a series of purely numerical data:
66. Event timestamps associated with a location.
67. The average movement over time, consider as HABITS.
68. The average location is HOME.


