# fitwit

FITWIT is the set of all IRL actions possible for you across decision-points. This is usually fewer than all imagined actions.

## Wit
Wit is all imagined actions.
Good wit(n) is those imagined that you will use or will inform good actions.
An example good wit is to not care about flavor in food. This enables possibility to enjoy more meals. If with company, this is a virtue ad mit seems universal.

Wit (v), as in cognition, mind, thinking, plan, goal. Good wit names changes in habit that increase alignment and pri with least effort and maintenence. Bad wit is closing off to such options, including action-guiding opinions that "rule" whether you go into the cold and sprint or try to catch the next bus.

The general WIT is ALT theory. In FITWIT below, ALTs are named as HYPE. 

Name HYPE that 
1-aligns PRIs. 0s are best.
2-you DO NOW (BLITZ).
3-DID before.
4-should (and could) DO. 

5-only if for science, 
  perfect HYPE with BET on 1--4.


## Fit
Perfect fit is when you take the best action possible with least hesitation and greatest efficiency, to achieve your goal.

Bad fit constrains the range of possible wit. You cannot run for a bus if you are too out of shape. 

## FITWIT
In all plans, consider the simplest possible solutions with the least sum effort of FIT and WIT (FITWIT). 

### 0s

HYPE 0s, such as
- "DO NOT DO"
- "DELETE"
- skip a meal or sleep instead of grocery shop. 

### 1-FIRE (BLITZ)
DO the GOAL NOW.

### 2-AIM
While 1,
FOCUS on the GOAL 

in-"Eye on the ball"

### 3-ADJUST
APPREHEND
- the progress and GOAL 
- HYPEs

VN-ADJUST
1-CHUD
2-PRI
3-FIRE

# x
- bitbet
- plan, navigation

## comm-problems
POINT
Dad and I don't know the other's knowledge.

### pitch
e-use
cord-coiled
i get and hold an extension cord, coiled.
while dad watches, i unravel some cord, and pause to try to understand and solve it.
dad was who last used the cord before storing it, and
he guesses my goal and points to the end of the cord to communicate what he knows.

maybe he doesn't know 
- my goal
- what i have seen and done to the cord since he used it last.
or maybe he does know.

if i trust he is right, i shift my attention to the end of the cord and try to solve the puzzle from there.
if he is 
- right, it saves me time.
- wrong, it costs me time. 

which risk is better?
to assume he is
- right or
- wrong?

## plan and vision
x-comm-essay-on_patronizing, etc.


## set a plan
look to the horizon
- pull the bit formerly of the intro
which talks of plans from the view of NOW.

## lock on it.
as soon as you set bearings,
it is on you to scrupulously determine the trueness of your DESTINATION.
(your path need only be as true as you need be expedient.)


## understand the logical detractions
there are many obstacles. flatten them, horizontally. that is, attempt to maintain a direct course, and ZERO (v) deviation of your angle.

how can you flatten them?


## keep moving.

keep moving toward your goal while practical.
resist planning, because it is stalling.
planning is an act of doubt.

faster to move than to plan to move faster
x-thoreau, walden
- you can get from pittsburgh to philly faster by walking than by train, so long as you walk right away in the right direction.
- to take the train requires a day or two's work to pay for the ticket, and then more time to wait for and take the ride.


keep digging the fencepost hole, if the auger doesn't start and the sledgehammer doesn't find. you have neither, nor are they goalfood.

count the cells in big data if you don't know how to code.
skim the sentences.
TDD scales you to function-writing.
