
# People {#people}  

## Places  

"Just like you, others are trying to figure out what goes on in their own garden.\*	people are different versions of each others' priorities ([see also c9.70][norms style])."
Amid the goals and forces of this chapter, none of what is described includes using words. reader, you will begin to understand their nature in the next chapter, bet, but as it pertains words that people use with each other, not until the last chapter, comm.
Consider people in terms of the four places of your life:  

    1. On your garden dealing with your self.
    2. On someone else's garden.
    3. At work making something for others for money.
    4. Getting something someone else made (market).

Sometimes you are at your garden's edge looking elsewhere.
For example, when you read an email or social media feed, as if looking across your neighbor's plot,
Studying how to bring your lettuce back to life, or celebrating your friend's successful pumpkin patch.  

## Gate  

Despite garden-based priorities, most of your time is spent outside your garden, and mostly for work (about 80,000 hours in your life).
Acknowledge the people in your priorities, yet don't let them distract.
Notice how long you leave your garden and to where.
Spend only as much time needed away for your priorities.
For example, most time on others' gardens, and any more than the minimum at work or market is cake. when in doubt, go home and stare at your plants. at least that cake is free.  

## Work  

Where do you get seeds for food from and how did you know to plant them?
From other people, right? No silly, you don't know how to garden a sandwich!
Lucky for you, many of the most important crops you want are already grown, prepared and handed to you--in exchange for money.
Money is traded for maintenance of, or insurance for self and cake, like apples, miracle medical procedures, and a toilet to take your poop somewhere else.
Work is performing a specific task on a collective garden, like an institution's in exchange for money. it is a pre-arranged visit to another garden for a specified time.
Whether or not you like it, or it directly fulfills garden needs, work is made to serve norms, not you.
Norms are all actions assumed of (or about) the "average" person. they are the web of forces of all actions of all people, including work, religion, popular attitudes, and doubts.

## Analysis  

If you have a job that pays you to think, your mind is hired to make norms products real.
Instead of your reality, your work is to translate norms's reality, chud-adjusted.
Norms assume you will work for money for goods.
Language, agreed usage of words, is made from norms.
Norms push against individuality (except where it provides a lucrative job opportunity).
Relationships are goals about people.
Good ones are aligned with your goals.
Bad ones cost more.
A relationship is a reciprocal pair of bets, yours of them, and vice versa. one is the better and the other is the bet and bet on.
Relationships, especially family members, coordinate many goals for savings.  

## Others  

Maybe they are your friend, and need help with some unruly vines, or maybe you just like their apples.
Sometimes, people will contribute to your goals, as if bringing water to crops you didn't recognize need them. 4. sometimes people will try to water your crops when they don't need watering.
Sometimes you'll return with higher morale or a bag of apples.
Sometimes you'll need to water some crops that need to be watered, because the sight of their neglect cannot be ignored.
The challenges that overwhelm you are the same for others, just not always the same amount nor at the same time.
The place, duration and impact on your priorities are the basic measurements of a relationship.
Pick work and relationships, including friends, that maximize your other priorities including possibly one that maximizes time and money to apply to other priorities.
Maximally align with norms with least compromise to priorities. get along with people.
people are the part of priorities that require the most care, and fewest words.
A good relationship is a contract of the reciprocated actions (use) between two people.
A bad relationship is hyped mutual bets (unaligned with actions), that waste time.  
