
# PPL  
## pushed in new work
### intro
Now is the time for you to see
what you probably expected to.
Every time you read an email,
look at social media or text,
you are at least at the perimeter of your garden
looking elsewhere,
but hopefully at least there-there

that's one side of 
relationship
BETs.
(The better bets on the world;
In a rltp, one is the better and
the other is the bet and bet on.

the other side
is all we do for you
that you need.
for so much of your
day, living awareness,
and dreams,
you are outside your garden
looking for a GOOD
for you.
Whether to keep you alive,
made and prepared food,
shelter,
you are gone.

(for most of us,
however,)
you're gone for most of the time
to WORK.

### first intermission
you have three places of life.
the first is on your garden
making your life and meeting your needs.
the second is away from your garden,
getting something someone else made,
for your needs.
the third is making something
at a job,
to get money so you can pay 
for those things others made
that you want.

the simple equation
that each of us solves
is this one;
what proportion
of time,
and for what goods,
do we spend at each of the three locations?

from these datum alone
we have all we need to know
as a psychological baseline
for each individual difference.

if you don't like
working for goods,
the good news is
you can go back to your garden
at any time.*
you will have to figure out what to do there,
but you're welcome to it.
stay in your house,
or plant something.
you'll need to learn a lot to make it worthwhile.

resolved:
come up with a planned ratio of time
spent at each.

spend only as much time needed
to work to 
earn only enough time learning
how to spend the least time needed
to make it real.


### part two: rules of work
the first rule of work
is what brought you here:
money.
you are here for it,
and in exchange you will
do something that at least one person
wants you do to.
if its a company, many people want it.

you can think of this simpler,
like a communist.
what you do is for another,
just like the basic cute way
you first imagined what it might mean
to go "visit" another's garden.


### part three: shared thinking
if you have a job
that pays you to think,
- (an analysis or coding or writing job for example)
then pay mind something most don't:
you are work for hire.
even if your subject-matter is reality
(which it usually should be to a good degree,
and also obscured by capitalist goals)
it is your job to
understand the shared terms of reality
and speak from it.
this is the opposite of
understanding reality from yourself.
of course it means starting
with your own understanding,
and then yet translating it
as you understand needs be
to speak what most know
the identical experience as.

let this section be the prequel
to peer-review
in education.

## Who are PPL 

1.	Just like you, others are trying to figure out what goes in their garden.\*	PPL are different VERSIONs of each others' PRI ([see also c9.70][NORMs STYLE]).

\* __You could think of people as seeds in your garden, but this is an over-application of seeds; and its unnecessary.__
2. Maybe they are your friend, and need help with some unruly vines, or 
maybe you just like their apples. 
3. Sometimes, PPL will contribute to your goals, as if bringing water to crops you didn't recognize need them. 4. Sometimes PPL will try to water your crops when they don't need watering.
5. Sometimes visiting their garden will bring up your morale, or get you a bag of apples to take home.
6. Sometimes you'll need to water some crops that need to be watered, because the sight of their neglect cannot be ignored.
7. Keep in mind that the challenges that sometimes overwhelm you are the same kind others deal with, but not always the same amount and at the same time.
8. How are PPL affecting your garden?

## WORK  

6.	Where do you get seeds for FOOD from and how did you know to plant them? 
7.	From other PPL, right? No silly, you don't know how to garden a sandwich! 
8.	Lucky for you, many of the most important crops you want are already grown, prepared and handed to you--in exchange for money.

9.	Money is traded for maintenance of, or insurance for SELF and CAKE, like apples, miracle medical procedures, and a toilet to take your poop somewhere else.
10. WORK is performing a specific task on a collective garden, like an institution's in exchange for money.
11.	You'll WORK about 80,000 hours in your life.

12.	Whether or not you like it, or it directly fulfills garden needs, WORK is made to serve NORMS, not you.
13.	NORMS are all actions assumed of (or about) the "average" person. They are the web of FORCES of all actions of all PPL, including 
WORK, religion, popular attitudes, and DOUBTS.
14.	Relatedly, NORMS assume you will WORK for money for goods. 
16.	Language, agreed usage of WORDS, is made from NORMS.
17.	NORMS push against individuality (except where it provides a lucrative job opportunity). 


20.	A FORCE is any cause of change. 
   1.	A FORCE underlies every action involved in a GOAL, yours or 
otherwise.
   2.	There are forces within your control, and forces outside.
21.	MAINTENANCE is the COST of FORCE to neither move toward nor 
away from a GOAL. 
22.	ALIGNMENT is when NORM or natural FORCE causes your GOAL to be 
more likely.
    1.	To ALIGN is to adjust your GOAL to be more like another force, 
usually one acting against your GOAL. 
    2.	Study how forces WORK against you. 

23.	Relationships (RLTP) are GOALS about PPL (PPL). 
24.	Good ones are aligned with your GOALS.
25.	Bad ones COST more. 
26.	A RLTP is a reciprocal pair of BETS, yours of them, and vice versa.
27.	RLTPS, especially family members, coordinate many GOALS for SAVINGS.

28.	Pick WORK and RLTP that maximize your other PRIS including possibly 
one that maximizes TIME and money to apply to other PRIS.
29.	Pick friends the same way. 
30.	Consider your actions and choices about PPL carefully. 
31.	Maximally ALIGN with NORMS with least compromise to PRIS. 
32.	ALIGN (get along) with PPL.

## The Classroom  

**Note: If this section is confusing, revisit it after "Ed".**  

33.	(No one chose to be born.) 
34.	Everyone begins life with their own unnamed and unanswered 
problems.
35.	Books can only tell a student what the answer is not (quite).
36.	The gap between problem and book answers is left for the student to 
"apply".
37.	A better approach would be to let the student define the problem 
through their reality and life GOALS.
38.	Let them write the PLAN and teach them only what is needed to 
succeed.
39.	Imagine a perfect course exists, designed to teach you to fulfill your 
specific ambitions. 
40.	Every aspect of what you NEED to know, that is known and 
communicable, is the only thing written. 
41.	Everything that cannot be known but must be discovered or practiced, 
is laid out as a set of instructions, described in the WORDS that 
maximize the learning opportunity, and your progress.
42.	Rather than a course in a classroom, the perfect class is a manual to 
reference as you live your life, or at least until you've internalized its 
contents: 
43.	when to take a break to strategize your decisions, lessons on what 
opportunities to watch for and resist, and so on. 
44.	Any social role you wish to take on, artist, engineer, therapist, 
insurance salesperson, reliable partner, is customized intimately, 
curated perfectly for what you need.
45.	Any relationship or interpersonal skill that is realistically possible for 
you is preceded with the guidance and education that prepares you 
emotionally to choose the right experiences that set you up to be 
most likely to find and make the most of opportunities to share 
yourself with another.

48. People, are the part of a theory of life that require the most care, and least words. 
49. Unlike the nature of our actions which play unconsciously and imply bets, 
50. Common, bad people activity is the habit of over-emphasizing mutual bets, and 
51. which fall out of alignment with actions.
52. Instead, consider a relationship to be only the actions that are reciprocated;
53. and call this the relationship 'contract.'

