---
output:
  word_document: default
  pdf_document: default
  html_document: default
editor_options: 
  markdown: 
    wrap: 72
---

# The I.B.C. {.unnumbered}

# Education

## The Classroom

1.  A CLASSROOM is a special case of MARKET and WORK; the direct and
    shared exchange of mental work, for the purpose of improving
    individual PRIs.
2.  No one chose to be born. Everyone begins life with their own unnamed
    and unanswered problems.
3.  Books are an author's answers; they can only tell a student what the
    answer is not (quite).
4.  Instead of teaching how to read between the lines, let the student
    define the problem through their reality and life GOALS.
5.  Let them write the PLAN and teach them only what is needed to
    succeed.
6.  Imagine a perfect course exists, designed to teach you to fulfill
    your specific ambitions.
7.  Every aspect of what you NEED to know, that is known and
    communicable, is the only thing written.
8.  Everything that cannot be known but must be discovered or practiced,
    is laid out as a set of instructions, described in the WORDS that
    maximize the learning opportunity, and your progress.
9.  Rather than a course in a classroom, the perfect class is a manual
    to reference as you live your life, or at least until you've
    internalized its contents:
10. when to take a break to strategize your decisions, lessons on what
    opportunities to watch for and resist, and so on.
11. Any social role you wish to take on, artist, engineer, therapist,
    insurance salesperson, reliable partner, is customized intimately,
    curated perfectly for what you need.
12. Any RLTP or interpersonal skill that is realistically possible for
    you is preceded with the guidance and education that prepares you
    emotionally to choose the right experiences that set you up to be
    most likely to find and make the most of opportunities to share
    yourself with another.

## Prompt

13. Is there a better version of you?
14. Are you capable of moving toward it?
15. Are you ready?
16. If your answers are yes, then you are a student. To live a better
    life, you will commit to change your actions.
17. First, you will learn what changes are needed.

## Admissions

18. This is a boot camp whose purpose is
    1.  to train adults to think harder, clearer and more effectively.
    2.  to produce intelligent solutions for personal and social
        puzzles.
    3.  to have a higher cognitive discipline.
    4.  to instill shared CAKE about reason, thinking and discourse.
    5.  to empower.
19. It is a training program designed to break down bad habits of
    thought, and build good ones while immersed here, a culture of
    rational thinking isolated from the outside world.

## Challenge

20. Here you will relentlessly confront your ideas about the world, with
    instructors drilling intellectual skills (writing essays, arguing
    for ideas, and developing proposals for action).
21. You will be trained to move toward your GOALS with focus, even in
    the face of perceptual, physical, or emotional distractions.
22. Over TIME, students could expect to cultivate a sharper focus on
    cognitive objectives, resilience to distractions and challenges.
23. If you graduate, it will be with the ability to identify, develop,
    and communicate ideal critical, rational arguments, positions or
    PLANS (orally or written) given the available knowledge, finite
    TIME, and resources at hand (reference material, teamwork).
24. you will also learn a code of behavior for being a community leader,
25. collaborating or competing with an irrational world.
26. The central requirement for applicants will be a commitment to
    better understand the SELF and world.

## Student

27. Students are PPL with IDEAS from EXPERIENCE toward selfish GOALS.
28. Lessons depend on students' prior knowledge.
29. A STUDENT
    1.  has a GOAL that can be better named and planned.
    2.  requires TIME away from BETTING.
    3.  admits not knowing but capable.
30. Students learn to represent their knowledge in WORDS; to prefer
    better, alternative WORDS. A student sees the impersonal as more
    reliable both for selfish GOALS and social ones.
31. A bad student studies to avoid action, or for its own sake.
32. A Student WRITES IDEAs and GOALS to their INSTRUCTOR.
33. Your GOAL is clear. You want:
    1.  The strength needed to take the right steps and make a habit of
        it,
    2.  keen eyes to estimate the destination and correct course, and
    3.  a focused mind to steady the foot.

## Consent

34. This is an in-person immersive experience.
35. You only really learn what you need to know to be who you really
    want. You won't learn unless you cannot escape needing it; in a
    dedicated environment that fosters acquisition, minimizes
    interference.
36. Whether you're here for the 7- or 30-day experience, you will WORK
    hard every minute.
37. For every minute of lesson on my TIME, students are to provide two
    minutes of writing, either toward others' learning or in direct
    application toward their GOAL.

## Course

38. Dedicate to identity growth. Be:
    1.  Quiet, except when tasks require verbal response.
    2.  Receptive to WORK and feedback provided by the instructor.
    3.  Committed to producing genuinely inspired ideas, working
        quickly, and seeking improvement.
    4.  Respectful that all are equal in voice, and aim to describe
        solutions with collective CAKE.
    5.  Receptive and responsive to prompts and observations (from peers
        and/or instructors) especially CHUD, vague language, and
        cognitive bias.
    6.  Motivated to describe solutions that benefit others, when
        possible, including peer-review.
39. Learn:
    1.  Precisely and only what is needed to trust a clear picture of
        what your life is.
    2.  First, how to make a PLAN, a map of who you are, and who you
        want to be;
    3.  Repeat Part one of this book, until your PLAN is good enough to
        be wrong, and truthful enough to hurt.
40. This will be the beginning of change, and the first test of your
    commitment.
41. Your performance is evaluated simply: whether or not you
42. end up eating, sleeping, thinking, talking, and acting differently.

## Think

43. Think, student.
44. Do not take notes, simply pay attention.
45. Everything I say is meant plainly.
46. If you get confused, forget it, and pay attention to right now.
47. Our GOAL here is thinking. Thinking happens in your heads.
48. Right now your job is to think about the truth you see in what i
    say.
49. A student has two roles to think in: Reader and Writer.

## READ

50. Read, student.
51. A reader is a listener and observer.
52. Reading is the same as listening to an instructor,
53. except that the speaking pace doesn't determine how fast you have to
    think, or remind you to
54. pay attention!
    1.  Your attention cannot be trusted on its own,
    2.  so lose distractions
    3.  like your smart phone.
    4.  You will befriend the simplest scientific instrument, a clock.
    5.  The clock is a cue to think.
    6.  When it goes off, get back on task.
    7.  The clock will babysit your unreliable attention.

## Truth

55. Your GOAL in reading is to isolate the truth from the lie.
    1.  Try reading this sentence:
    2.  "Everyone is best off running weekly until they die."
    3.  You're thinking, "this can't be true for everyone, so it's a
        lie."
    4.  Not so fast.
    5.  There are many components to this idea, and likely many that you
        believe are truthful.
    6.  Often a lie becomes true just by changing the pronouns in the
        text.
    7.  Consider this revision: "I am best off running weekly until I
        die."
    8.  Perhaps now the WORDS are more truthful to you.
56. Doing this makes a clear relationship between your belief and the
    author's.
57. Becoming smart is the discipline of understanding how you relate to
    others.
58. When reading, dismiss only what you fully believe is an intentional
    lie.
59. More generally, read to assess your BET on the WORDS reflecting
    TRUTH.
60. Whether to a single WORD, a line, chapter, or book.
61. Assign WEIGHTs (0 to 9) to what you read, to complete this prompt:
62. I BET this is true for:
    1.  0 = not even the author.
    2.  1 = only the author.
    3.  2 = the author, me, and a few others.
    4.  3 = Us and 30% of everyone else.
    5.  9 = Us and about 90% of everyone else.
63. For every assertion and assumption you read, begin assuming it is a
    "9", working backwards according to evidence you hold.

## Lesson

64. The following mini lesson illustrates the risk at hand--involuntary
    comprehension, and the benefit at stake from deliberate reading.

65. Consider the following quote, "Change your thoughts to change your
    life."

66. Comprehension is involuntary.

    1.  You cannot help but recognize meaning when you read.
    2.  This means that you likely thought the quote was largely
        unrealistic.

67. Reading as proposed here, is strongly voluntary.

68. For example, reread the quote, this TIME assuming it is reasonable,
    serious, and valuable.

69. The statement is the core assumption to this book, and any
    psychological theory.

70. For example, Freud's talk therapy was, in his TIME, the radical idea
    that WORDS could fix PPL.

71. Therefore, do not waste the opportunity to consider a truth that
    could change your life by failing to entertain a simple assumption.

## Say 

72. How will your life look if you put it on paper? Like a bunch of
    WORDS.
73. How do you change it? By deleting the WORDS with lies, and replacing
    them with better WORDS.
74. The right WORDS will change your actions and your life. To live a
    better life, starts with your WORDS.
75. In order to do something about thoughts, we need to think on paper.
    [You'll write a lot. You'll delete a lot. You'll get good at
    writing.]

## WRITE 

76. BET on WORDS. A writer invests TIME and energy to map feelings onto
    WORDS.
77. Good writing is discovering, curating, and applying insight. Bad
    WRITING has an author; ad hominem.
78. Revisions also make you a WRITER. When you revise WORDS (yours or
    others') to maximize your BET, you are a writer.
79. Separate thought and SELF (author), by BETTING explicitly.
80. State your assumptions, do not justify them. -is-STYLE-bad
81. Replace "I am." with tag WORDS.
82. Strive for COMM-CONTENT and brevity; Write only valuable BETs, or
    WORDS that manifest valuable BETs. Prioritize understanding over
    original writing.
83. WRITING for LIB-PPL, relatable, depersonalized, objective WORDS,
    minimizes rot, maximizes PLAN utility.

## Instructor

84. I am an instructor, a guardian of true IDEAs and WRITER of a general
    PLAN (this book).
85. An instructor READS, and enforces BETs on LINKs toward a PLAN.
86. My GOALS are to
    1.  Minimize student effort and TIME to write.
    2.  READ for cognitive biases, illogical appeals, and imprecise
        language, and WRITE feedback that is dispassionate and neutral,
        yet invested and True.
    3.  Reward arguments based on (Truth:) REALITY, SELF, and CAKE.
    4.  Reward IDEAS shared (vs kept).

## Answers

87. Which lines from this book would you [BET on][How to Read], written
    as-is, or revised for you?

88. Assign 100 dollars (total) to those lines according to their
    relative impact, and you are an IBC student; an author of shared
    truth.

89. Suppose a representative set of PPL did the same thing. Here's a
    game to help imagine.

    1.  Each student's bets go to a general pool.
    2.  When bets on a line reach a critical mass, the pool of sub-par
        bets is split among winners.
    3.  Cash is divided.
    4.  Also, points are recorded, to incentivize a deeper purpose:
    5.  A game, where the prize is
    6.  the collective revision and authorship of this book.
    7.  After x wins, your name appears on the title.
    8.  High scores are on the acknowledgements page.
    9.  This is the process and meaning of READER and WRITER; bound
        directly to material and action, IRL.

90. Whereas the exchange of MONEY incentivizes the revision of truth,
    the CONTENT itself would be the premise to the next book, [the
    Answerword][The Answerword].
