---
output:
  word_document: default
  pdf_document: default
  html_document: default
---


#	(PART) The I.B.C. {-}
# Education

## Intellectual Bootcamp 
### Prompt 1

1.	On the computer screen:
Consent and Commitment
2.	Hi.
2.1.	 Is there a better version of you?
2.2.	 Are you capable of moving toward it?
2.3.	 Are you ready?
3.	If your answers are yes, then you are a student. 
4.	To live a better life, you will commit to change your actions. 
5.	First, you will learn what changes are needed.

### Admissions 
6.	This is a boot camp whose purpose is 
6.1.	to train adults to think harder, clearer and more effectively. 
6.2.	to produce intelligent solutions for personal and social puzzles.
6.3.	to have a higher cognitive discipline.
6.4.	to instill shared CAKE about reason, thinking and discourse. 
6.5.	to empower.
7.	It is a training program designed to break down bad habits of thought, and build 
good ones while immersed here, a culture of rational thinking isolated from the 
outside world. 

### Challenge yourself  

8.	Here you will relentlessly confront your ideas about the world, with instructors 
drilling intellectual skills (writing essays, arguing for ideas, and developing 
proposals for action).
9.	You will be trained to move toward your GOALS with focus, even in the face of 
perceptual, physical, or emotional distractions. 
10.	Over TIME, students could expect to cultivate a sharper focus on cognitive 
objectives, resilience to distractions and challenges. 
11.	If you graduate, it will be with the ability to identify, develop, and communicate 
ideal critical, rational arguments, positions or PLANS (orally or written) given the 
available knowledge, finite TIME, and resources at hand (reference material, 
teamwork).
12.	you will also learn a code of behavior for being a community leader,
13.	collaborating or competing with an irrational world.
14.	The central requirement for applicants will be a commitment to better 
understand the SELF and world.

## Student

### Student GOAL  

15.	Students are PPL with IDEAS from EXPERIENCE toward selfish GOALS.
16.	Lessons depend on students' prior knowledge.
17.	A STUDENT
17.1.	has a GOAL that can be better named and planned.
17.2.	requires TIME away from BETTING.
17.3.	admits not knowing but capable.
18.	Students learn to represent their knowledge in WORDS; to prefer better,
alternative WORDS. A student sees the impersonal as more reliable both for 
selfish GOALS and social ones.
19.	A bad student studies to avoid action, or for its own sake.
20.	A Student WRITES IDEAs and GOALS to their INSTRUCTOR.
21.	Your GOAL is clear. You want 
21.1.	The strength needed to 
21.1.1.	take the right steps and
21.1.2.	make a habit of it, 
21.2.	 keen eyes to 
21.2.1.	estimate the destination and 
21.2.2.	correct course, and 
21.3.	 a focused mind to steady the foot.

### Agreement-1

22.	This is an in-person immersive experience.
23.	You only really learn what you need to know to be who you really want. You 
won't learn unless you cannot escape needing it; in a dedicated environment 
that fosters acquisition, minimizes interference.
24.	Whether you're here for the 7- or 30-day experience, you will WORK hard every 
minute.
25.	For every minute of lesson on my TIME, students are to provide two minutes of 
writing, either toward others' learning or in direct application toward their GOAL.

### Student PLAN 
26.	Dedicate to identity growth. Be:
26.1.	Quiet, except when tasks require verbal response.
26.2.	Receptive to WORK and feedback provided by the instructor.
26.3.	Committed to producing genuinely inspired ideas, working quickly, and seeking improvement.
26.4.	Respectful that all are equal in voice, and aim to describe solutions with collective CAKE.
26.5.	Receptive and responsive to prompts and observations (from peers and/or 
instructors) especially CHUD, vague language, and cognitive bias.
26.6.	Motivated to describe solutions that benefit others, when possible, 
including peer-review.

### Course Content  

27.	Now, what is it you'll learn? 
27.1.	Precisely and only what is needed to trust a clear picture of what your life 
is. 
27.2.	First, how to make a PLAN, a map of who you are, and who you want to be; 
27.3.	Repeat Part one of this book, until your PLAN is good enough to be wrong, 
and truthful enough to hurt.
28.	This will be the beginning of change, and the first test of your commitment. 
29.	Your performance is evaluated simply: whether or not you 
30.	end up eating, sleeping, thinking, talking, and acting differently.

## Roles
### Think  
31.	Think, student. 
32.	Do not take notes, simply pay attention. 
33.	Everything I say is meant plainly. 
34.	If you get confused, forget it, and pay attention to right now.
35.	Our GOAL here is thinking. Thinking happens in your heads.
36.	Right now your job is to think about the truth you see in what i say.
37.	A student has two roles to think in: Reader and Writer.

### READ Attention  
38.	Read, student.
39.	A reader is a listener and observer.
40.	Reading is the same as listening to an instructor, 
41.	except that the speaking pace doesn't determine how fast you have to think, or 
remind you to 
42.	pay attention!
42.1.	Your attention cannot be trusted on its own, 
42.2.	so lose distractions 
42.3.	like your smart phone.
42.4.	You will befriend the simplest scientific instrument, a clock. 
42.5.	The clock is a cue to think. 
42.6.	When it goes off, get back on task.
42.7.	The clock will babysit your unreliable attention.

### How to Read
43.	Your GOAL in reading is to isolate the truth from the lie. 
43.1.	Try reading this sentence: 
43.2.	"Everyone is best off running weekly until they die." 
43.3.	You're thinking, "this can't be true for everyone, so it's a lie." 
43.4.	Not so fast.
43.5.	There are many components to this idea, and likely many that you believe 
are truthful. 
43.6.	Often a lie becomes true just by changing the pronouns in the text.
43.7.	Consider this revision: "I am best off running weekly until I die." 
43.8.	Perhaps now the WORDS are more truthful to you. 
44.	Doing this makes a clear relationship between your belief and the author's. 
45.	Becoming smart is the discipline of understanding how you relate to others.
46.	When reading, dismiss only what you fully believe is an intentional lie.
47.	More generally, read to assess your BET on the WORDS reflecting TRUTH.
48.	Whether to a single WORD, a line, chapter, or  book.
49.	Assign WEIGHTs (0 to 9) to what you read, to complete this prompt:
50.	I BET this is true for:
50.1.	0 = not even the author. 
50.2.	1 = only the author. 
50.3.	2 = the author, me, and a few others.
50.4.	3 = Us and 30% of everyone else. 
50.5.	:
50.6.	9 = Us and about 90% of everyone else.

51.	For every assertion and assumption you read, begin assuming it is a "9", working 
backwards according to evidence you hold. 

### READ PITCH  
52.	The following mini lesson illustrates the risk at hand--involuntary 
comprehension, and the benefit at stake from deliberate reading. 
53.	Consider the following quote, "Change your thoughts to change your life." 

54.	Comprehension is involuntary. 
54.1.	You cannot help but recognize meaning when you read.
54.2.	This means that you likely thought the quote was largely unrealistic.
55.	Reading as proposed here, is strongly voluntary.
56.	For example, reread the quote, this TIME assuming it is reasonable, serious, and 
valuable. 
57.	The statement is the core assumption to this book, and any psychological 
theory.
58.	For example, Freud's talk therapy was, in his TIME, the radical idea that WORDS could fix PPL.
59.	Therefore, do not waste the opportunity to consider a truth that could change 
your life by failing to entertain a simple assumption.

### Write PITCH

60.	How will your life look if you put it on paper? Like a bunch of WORDS.
61.	How do you change it? By deleting the WORDS with lies, and replacing them 
with better WORDS.
62.	The right WORDS will change your actions and your life. To live a better life, 
starts with your WORDS.
63.	In order to do something about thoughts, we need to think on 
paper. [You'll write a lot. You'll delete a lot. You'll get good at writing.] 

### WRITE PLAN  
64.	BET on WORDS. A writer invests TIME and energy to map feelings onto WORDS.
65.	Good writing is discovering, curating, and applying insight. 
Bad WRITING has an author; ad hominem
66.	Revisions also make you a WRITER. When you revise WORDS (yours or others') 
to maximize your BET, you are a writer.
67.	Separate thought and SELF (author), by BETTING explicitly.
68.	State your assumptions, do not justify them. -is-STYLE-bad
69.	Replace "I am." with tag WORDS.
70.	Strive for COMM-CONTENT and brevity; Write only valuable BETs, or WORDS 
that manifest valuable BETs. Prioritize understanding over original writing.
71.	WRITING for LIB-PPL, relatable, depersonalized, objective WORDS, minimizes rot, maximizes PLAN utility.


### Instructor 

72.	I am an instructor, a guardian of true IDEAs and WRITER of a general PLAN (this book).
73.	An instructor READS, and enforces BETs on LINKs toward a PLAN.
74.	My GOALS are to
74.1.	Minimize student effort and TIME to write.
74.2.	READ for cognitive biases, illogical appeals, and imprecise language, and 
WRITE feedback that is dispassionate and neutral, yet invested and True. 
74.3.	Reward arguments based on (Truth:) REALITY, SELF, and CAKE. 
74.4.	Reward IDEAS shared (vs kept).

## Book of Answers  

1.	Which lines from this book would you [BET on][How to Read], written as-is, or revised for you? 
2.	Assign 100 dollars (total) to those lines according to their relative impact, and you are an IBC student; an author of shared truth.

3. Suppose a representative set of PPL did the same thing. Here's a game to help imagine.
3.1.	Each student's bets go to a general pool.
3.2.	When bets on a line reach a critical mass, the pool of sub-par bets is split among winners.
3.3.	Cash is divided.
3.4.	Also, points are recorded, to incentivize a deeper  purpose:
3.5.	A game, where the prize is
3.6.	the collective revision and authorship of this book.
3.7.	After x wins, your name appears on the title.
3.8.	High scores are on the acknowledgements page.
3.9.	This is the process and meaning of READER and WRITER; bound directly to material and action, IRL.

4. Whereas the exchange of MONEY incentivizes the revision of truth, the CONTENT itself would be the premise to the next book, [the Answerword][The Answerword].

