

# WORDS 

## Cognition 
### PITCH  
1.	WORDS describe the world and its conditions.
2.	This chapter is about issues and solutions regarding the ACT of describing, itself.
    1.	WORDS said do not usually reflect what PPL want or need.
    2.	By engaging the gap between WORDS and reality, you increase SELF-awareness (BET).
    3.	Better WORDS mean more practical understanding and expectations, more complete desires, and 
    4.	the capacity to make a concrete PLAN for achieving your GOALS. 
    5.	This will include healthier COMM and RLTPs.
    6.	A community with better WORDS has clearer idea sharing, 
synthesizing, developing, teaching and learning.

### Problem  

11.	Speaking your mind is difficult to do accurately.
12.	A memory system dealing with language is tasked to translate 
thoughts into the right WORDS from tens of thousands.	It is prone to inaccuracies.
13.	Similarly, a listener focused on comprehending, is not likely to monitor all the incidental priming effects of WORDS on a memory system. 
14.	WORDS said and heard impact both parties' beliefs and behaviors. 
15.	Saying WORDs or Hearing and understanding a WORD is a very small physical action, to describe real actions and consequences.
16.	The issue is that WORDs can be more and less right, more and less helpful, and without intervention, it is very difficult to know how much this is true in any example of WORD USE.
27.	Bad WORDS keep CHUD expensive and waste TIME.
28.	The COST of an individual WORD is tiny, but we say tens of thousands per day (Levelt). 

### WORD as BET  

20.	A GOOD general BET about WORDs is to begin assuming every WORD is a BET on hypotheticals, which can be true (reality) or false (fantasy/lie).
21.	A PLAN is a BET on a winning arrangement of WORDS that result in the GOAL.
22.	Reading, thinking, saying, and writing a WORD perpetuates that WORD's IDEA over others, either moving you toward a GOAL, or your HABIT.

### SIM
23.	WORDS efficiently simulate possible worlds. You can think through far more situations with WORDS, than you can (or should) act out. 
24.	Your GOALS can be described in WORDS, and WORDS can be easily crossed out and revised.
25.	Good WORDS maximize productivity of thought, move you beyond 
pitfalls of CHUD, direct attention to PRIS, and predict reality; improve decisions and make you smarter.
26.	By thinking about all WORDS you experience (LIB), you can take control to limit your WORD use toward more productive ones, 
improving READ and WRITE decisions, increasing focus and TIME for GOALS.
27. SIM (F-ACT) is the act of iterating between WRITE and READ, to evoke and NAME the optimal, held BET. Tour SIM is not constrained by IRL, but your picture of IRL, and your SIM GOAL is to capture the picture true to your CHUD estimate.


## Speak/Write
### WRITE PLAN  

30.	Speak, write, initiate or respond only in limited duration and WORDS 
dictated by intended outcome. 
31.	Use WORDS empirically, with a comparison group (vs) and quantity in 
mind.
32.	Ideas are more important than authorship. 
33.	Do not use a WORD that is more of a Lie. 
34.	Say the truth or be quiet. 
35.	Use WORDS for decisions, not emotions. 
36.	Use WORDS to facilitate PRIS. Do not write PLANS you won't follow. 
37.	Stop talking when action (or listening) is needed.

### READ PLAN

38.	Listen / read when you need to learn / connect. 
39.	Limit duration/WORDS needed to assess consent.
40.	Distrust ego, and take nothing personally 
41.	Investigate the empirical CAKE of WORDS.
42.	Revise to believe, and revise PLANS into ones you'd follow.
43.	Remove / ignore style. 
44.	Assert boundaries against exaggerated WORDS or unreliable ones.

## Types
a description of the kinds of simulation a word can make, and the kinds to prioritize.

### EXAMPLE and IDEA

45.	An EXAMPLE is an individual, particular event or object, of reality. 
    1. An example with consequence is a USE-CASE. 
    2. An example in-principle is a HYPE (hypothetical/hype). 
    3. In COMM, EXAMPLES are described per the criteria that might support a USE of an EXAMPLE.
    
46.	WORDS are one of two types:
    1.	LINKS: WORDS that give relationship between EXAMPLES, IDEAS, describe ACTIONS, ROLES, and transformations.
    2.	IDEAS: WORDS that refer to EXAMPLES.
    3.	An IDEA is a set of criteria that LINK EXAMPLES as similar (vs not).
    4.	The most basic IDEA classifies EXAMPLES as A or not-A. "blue" is 
an IDEA that certain colored things are BLUE (A), and all other 
colors are not BLUE.
    5.	Good IDEAS group EXAMPLES in a way that directs attention
toward PLANS and GOALS. Bad IDEAS distract.
    6.	The right LINK between ideas is the foundation of every thought, RECIPE or terrible calculation.

### Types
47. HYPE vs USE-CASE guides what and if to write. A GOAL is a named HYPE. GOOD HYPE are worthwhile GOALs, sub-GOALs, or ALT PLAN ACTIONs to consider. Don't WRITE HYPE without a BET.
48. As all words should be toward PRIs, there are three general modes of PRI WORDs: 
    1. h0 = history. HABIT is to history as action is to DOC. GOOD history is structured data of your HABIT, expressly for the purpose of revising future actions.
    2. h1 = plan (pri.txt, proj_doc.txt)
    3. h2 = doubt especially for bet. 

49.f. ALTs are any IDEA which measurably deviates a PLAN, and are defined directly with respect to the target IDEA. For example, BAD is an ALT to GOOD, as in "GOOD-vs-BAD".

50. Any other valid modes, if at all, are in support of maximal revision in these primary ones. 

51. A PLAN comprises: 
    1.the decided action,
    2.the best bet on it,
    3.alternative actions, 
    4.the goal,
    5.the relevant CHUD.

52. GOOD GOALs and their PLANs are supported by USEs from your own history (SELF-H), and next best is NORM or OTHERS' USE or DATA that generalizes. For example, a plan for a similar goal has previously succeeded.

### Letters
Add tags as a prefix to the dash 
to assert the kind of LINK between ideas.
(Prefixes are not exhaustive or mutually exclusive.)
  
1.  `f` define; function  
2.  `i` synonym, sense, "i.e.", "as in",  
3.  `e` example, data-point, untested data  
4.  `h` history (implied h0)
5.  `h1` claim, thesis. vs h0 or h2.

6.  `x` Cross-references, xref  
7.  `d` Data or evidence, summary

8.  `v` version / revise  
9.  `vs` an alternative, sibling of a shared parent category.


Abbreviations I use less often.
11.  `a` assumption or attribute  
         x-[link-f]  
         x-(pri-lesson-chess life 2021-03-07.txt)  
12.  `w` write (verb)
13.  `n` next task  
15.  `t` theory, rationale, frame

## NOTEs 2
Good NOTES clarify PRI (CONTENT) within BETS from secondary ones (I-STYLE) 

### PAR
In a DOC, PAR is a GROUPED set of WORDs roughly equivalent to a complex sentence. It has a primary subject and predicate, and includes any immediately relevant branches from either. In practice it is between 1 and 4 clauses.

GOOD PAR successfully denotes a LINK between two IDEAs, with the following FORM: 
    1. a syntactic tree, where  
    2. [newline] is the right path in a fork,  
    3. first indent (" -") is the left path in a fork,  
       - trailing "-" denotes all subsequent lines 
         in section are equal childs.   
    4. subsequent newline indents or in-line "--" are siblings  
    5. left to right are siblings  
    6. double linebreak ends the local tree.  
  
when word order is a left-to-right walk of 
a right-branching syntactic tree, 
sentence can be written in lines of random lengths, and 
read equally as unambiguously. 

### goals
reference and vocabulary
- restrict to simple or plain english to reduce amibiguity
v-syntopicon

### names
make folder and file names
i-goals
as transparent as possible
- imply or reveal its (hidden) members.
  i-iconicity

promote (i-consolidate; 2 -> 1)
- only-childs
- esp hf ones

example
- ppl-work -> work
- self-home -> home

xref
- lang-prod-abstract labels' 
  - systematicity does, can adhere to this.
  - when creating or reusing a word for new applications, this principle should be a factor
  - filenames are an everyday example of this.

## NOTES and DOCs  

35.	NOTES are REVISION PLANs.
36. What follows is illustrative (not exhaustive) of GOOD NOTES. More detail available on request.

37. Follow a RECIPE format to preserve the value of insights.

### RECIPE

35.	A Recipe is one of the best ways to arrange PLANS.
36.	Lessons and instructions use a RECIPE format. 
37.	The RECIPE format highlights the IDEAS and LINKS of your point and minimizes excessive STYLE.
    1.	List key IDEAS.
    2.	Describe actions and transformations (LINKS).
38.	Given an IDEA, estimate relevance to PRIS, problems, undeveloped PLANS, and SELF-MAINTENANCE.
39.	Keep docs short enough that the title and CONTENT address only one 
thing.
40.	Save selectively and
41.	delete frequently.

### 1. A word is a doc
when it is saved 
with a name, at least once.
2. Word is to a GOOD DOC (for example, a resume),
as action is to goal.
3. To a BAD DOC, a word (for example a diary entry)
is to an unnecessary purchase at a tupperware party.

links to named pris
- notes: words for comm
- lib: what words to save
- revision: words for pris

### 2. introduce ideas in unambiguous terms.
- introducing a new topic, provide a succinct, distinctive illustration of the point or merit, *in the verbiage you will most likely understand*.
- then describe the link with a taxonomic reference, as follows, where each idea read left to right is a type of or label for the preceding category, implying alternatives at each level.
  e-psych-teach-2021-unit4-hw-methods_report-intro 
    "For this assignment, consider your grandparents."

### 3. Illustrate the link 
At a micro-scale, every dash itself is a link.
for example, in the taxonomy, 
"Psych-teach-2021-unit4" the three latter IDEAS qualify the topic, PSYCH. The order of terms from left to right should closely correspond to the order of relevant conditional differences that determine:
1) the pri for the reader. answer: what are the fewest words to help a reader know a topic is irrelevant or truly beneficial?
2) the most similar and relevant concepts to most distinct, rare, and particular to what is being described. 
  1. the left-most word will be either implied or actual chapter headings. All science that is not directly relevant elsewhere, will fall under PPL-WORK or SELF-HOME. The remaining chapters deal with modes on these basic sources: PRI and ED concern optimizing life. (What about WORD, REVISION, COMM?)
In the example above, PSYCH might fall under SELF-BODY, SELF-HOME, PPL, PPL-WORK. 
Here, we are talking about defining links for purposes of reducing ambiguity. 
The link is the decision of the sentence that requires the most care. It is simply a bridge, and as such has a basic and plain function. 
Named links are ACTIONS.

Over-spelling the IDEAs leaves an empty link, e-"do...(the trash)"
consider what is the manner of spending time, if an action, to ascribing your link.
Consider the specific change being undertaken.
Some ACTIONS:
TAKE, GIVE, MAKE, BUY, SELL, 
USE/EAT, WORK, WRITE, READ.
- Notice these are all verbs of transfer.

In instr, the link comes last, and it describes a step in revision.

### 4. Contextualize with an alternative
a plan should inherit or give definitions of new terms.
new definitions should especially be accompanied by a true use-case,
to protect against a false problem.
a pri is the motive for life, and itself is only a named spending of time.
a developed pri is an instruction.
one generalized is a lesson.


### ROLE Scientist

47.	A scientist works to win BETS against the UNKNOWN. They are a 
professional writer, evaluated on two metrics:
    1.	For their new CONTENT. 
    2.	The net benefit on GOAL outcomes.
 
    
48.	A scientist-researcher is a WRITER, a data-collector and hypothesis tester. 

49.	A scientist-scholar is a READER, curating toward theory development and COMM.

More will be said about SCIENTIST more broadly. Here we focus strictly on the aspect of a scientist which is to develop the description of the world, properly. 

## T-WIT ACT-Types 
A general framework for testing a "cognitive unit". 
NEXT: Thread through SR constraints, against PRI.

What metric can be used to compare and test BETs on WORDs?
Such a metric requires a general framework for cognition 

FRAMEWORK (FRAME) is a cluster of definitions.

### PITCH
just as a child learns skills
from put it in the box
to put it together, 
and you need to solve
the problem you creatively set up
to solve the impossible,

so too
the highest cognitive function
--these days a cooperative one
beyond the speed or control
of any individual--
deserves treatment
of its abilities and applications
in order of processing difficulty
and utility.
- utility in contributing to itself however it sees fit,
- but especially in its allocation of finite resources.

### THEORY 

$$ H1  
where P = Cognition,
GOOD.P = P(WIT.GOAL.SORT|PRI) $$

cognitive acts should be engaged in as a pyramid of levels (like food pyramid),
number of tasks (width of level),
e-base of 4 height of 4 (levels)=4 topics on bottom level, 3 on 2nd, 2 on 3rd and 1 on 4th.
where the bottom level is the simplest of tasks, such as
name and or bin,
the next is between order and sort, 
then between measure and assemble, 
finally between test and use, 
until it leaves the pyramid as habit, extinguished, or tasks revised. 

For example, assuming a GOAL, make an action plan (BLITZ) constrained by number of tasks by type as follows: 
    5. SORT
    4. NAME, DEF, or MEASURE,
    3. MAKE (minimum viable)
    2. TEST (EDIT, SIM, REVISE)
    1. USE  (reliable, helpful)

additional tasks must "wait" to be addressed until a task of the same level becomes complete and removed from the pyramid, leaving a slot to be replaced. 

this is a frame that gives a starting point for assessing how and what optimal capacity and boundaries exist for a human as a cognitive being.


### GOOD SIM EXAMPLE 
The IRL test is a BET. Above is a proposed initial BET, arrived at by SIM. 
GOOD SIM step 
1. NAME a PRI-scope of IRL-events. 
2. For example, tasks may differ in how hard and many times actions at various levels need be done; 
3. The following properties can be varied by SIM. 
    1-TASK type definitions, pyramid level definitions.
    2.TASK-LEVEL and TASK-COUNT
    3. For example, 3 levels starting at 10-count, reducing by 2 (10,8,6), or 5 levels start at 25 reducing by 6 (25,19,13,7,1).
4. The GOAL of SIM is to maximize a BET you take (e.g., vs defining relevant PRIs).
    

