# Change

## Revision

1.  Neutrally, a WORD may be replaced by another. As a process which takes effort, do so to improve, and we will call it REVISION. REVISION is the change of WORDS to improve actions of yourself or others.

2.  REVISION is how we know reflection is happening, described here in VERSIONS (v#) of a response.

3.  For example, consider the following revisions (v1-3) describing this brief argument:

    1.  1: "Nobody follows doctors' orders."\
        2: "My parents do, religiously."\
        1: "They're the exception."\
        2: "You're not exposed to minorities."

    2.  v1

        a)  1 makes a false generalization.
        b)  2 illustrates a counterpoint, and 1 gets mad.
        c)  1 dismisses it, and 2 gets mad.

    3.  v2

        a)  1 generalizes from WORK experience.
        b)  2 argues with parents' experience, and 1 gets mad.
        c)  1 dismisses and 2 get mad.

    4.  v3

        a)  1 argues outside 2's experience.
        b)  2 uses personal experience, thinking it's impenetrable.
        c)  Failing and hurt, 2 insults.

4.  The example aims to illustrate revisions which increase the amount of responsibility, control, and preventable future behavior on part of the writer, without much change in WORD count.

## Plan

5.  Good revisions better describe what we know to have happened, and predict what will happen (again).
6.  Reality is what determines whether each version is better.
7.  Revise prior prompt responses only to help your current prompt response.
8.  If your GOAL deals with different assumptions about the truth, change the prompt to whatever gets you to write the most helpful WORDS for your GOAL.
    1.  For example, a prompt referring to University student experiences should be adapted for your non-University experiences.
    2.  A common (problematic) assumption is that you are emotionally ready to be SELF-critical.
    3.  Do not change the prompt so you can be lazy.

## Think!

9.  Elsewhere, we will establish variations on ultimate questions.
10. One variant is the superlative presupposition, which becomes an imperative (PLAN).
11. For illustration, all questions presuppose and command, "Think!"
12. As compliment, all WORDs can be seen as an answer to this question (GOOD or BAD).
13. Supposing just as questions can be revised to their superlatives, we don't bother to ask them, and focus on the superlative of answers.
14. Thus is an example basis of GOOD revision: to bring the particular apprehension to a universally relevant call to action, responding to the implied imperative of all questions, "Think."

## Plan

15. The GOAL of WORDS is to express ideas of maximum CAKE tomorrow.
16. Since few WORDS meet these criteria, start by revising toward fewer WORDS.
17. Make IDEAS clear and concrete.
18. Provide just enough CONTEXT to remember the basis of the key ideas.
19. Precision depends on purpose.
    1.  LIST. Name relevant ideas for GOAL.
    2.  WRITE a PLAN, (ordered LINKS).
    3.  DOUBT. Assert the strongest rebuttal to the PLAN.
    4.  BET. Improve IDEAS and LINKS by addressing weakness and clarity.
    5.  READ. Wager its CAKE (e.g., Relative to another PLAN).
20. When reflecting, reflect only on "how can I help my future SELF?" And impose TIME and WORD limits.
21. A bad doc is stream-of-consciousness.

## Prompts

22. Prompts elicit conflicts (truth) between SELF and NORM, to improve PLANS for your GOALS.
23. TIME and WORD limits WORK together to encourage a balance between reflecting on truth and describing it.

## Word Limit

24. WORD limits combat needless WORDS and distracting tangents. A WORD limit keeps your attention.
25. A WORD limit is a proxy for a prompt's complexity.
26. Try to write the exact number of WORDS.
27. Good WORD limits require cutting out unhelpful WORDS, change figurative WORDS to concrete, ideally assertive and falsifiable.
28. For every PLAN you make: Assert a WORD limit before writing to be reminded of your initial intentions, and be challenged to express ideas clearly. Become skilled at using only the fewest WORDS necessary, to reveal and clarify CAKE.
29. If you exceed the limit and there is no end in sight, stop and reassess.

## Time Limit

30. The TIME limit dictates how precise your WORDS should be.
31. Use extra TIME to improve WORD choice.
32. For example, given a 50-WORD limit, 1 minute (1m, 50w) encourages free writing with minimal restrictions on quality of thought, while 4 minutes encourages more careful selection of WORDS.

## LESSONs

33. LESSONS are an ordered set of prompts, usually three to four, up to 60 minutes and 250 WORDS. A prompt's WORD count is the number of WORDS to be added to your document.
34. Lessons target inconsistencies between reality and PRIS.
35. They are designed to be revisited and revised repeatedly.
36. A 0w prompt means revise, but do not increase the WORD total.
37. The first prompts in LESSONS are warm-ups to direct your attention. They ask for names of IDEAS.
38. The remaining prompts are for thinking, requiring you to make LINKS between your warm-up IDEAS. Done right, you will face some new truths.

## PEER-REVISION

39. Peer revision is a powerful learning tool. Get answers from others. 
40. Forget who provides REVISION and how much. 
41. The peer WRITER has uncompromised objectivity, and liberty to employ Truth, however "harsh".
