
# Index of Definitions

1. IDEA definitions in order of appearance. 
2. This is currently statically generated, so there are slight discrepancies with definitions in main text. (Last revised: v2.15).

**c2.38.**	A GOAL names an ideal future outcome, and requires a PLAN to intentionally achieve it.  
**c2.44.**	A PLAN comprises WORDS that facilitate your GOAL.   
**c2.49.**	A COST is what's materially required for GOALs--an amount and kind of FORCE.  
**c2.56.**	FOOD is the necessary and sufficient material to satisfy these needs.  
**c2.57.**	CAKE is all non-FOOD GOALs.  
**c2.58.**	SELF is the GOAL to MAINTAIN HABIT, ideally to maximize BET outcomes ([c5.28][BET]).  
**c2.59.**	HOME is the collection of tools, materials and money (which support HABITs).  
**c3.33.**	PRI is the GOAL to manage the set of GOALS in your life (and common themes therein).  
**c3.38.**	TIME is the constant (or denominator) for PRI and FORCES (LIB and MEMORY).   
**c4.09.**	MONEY is traded for maintenance of, or insurance for SELF and CAKE.  
**c4.10.**  WORK is performing a specific task on a collective garden for MONEY.  
**c4.13.**	NORMS are the "average" person's HABITs, including WORK and CHUD.  
**c4.20.**	A FORCE is any cause of change including actions.  
**c4.21.**	MAINTENANCE is any recurring COST to neither move toward nor away from a GOAL.   
**c4.22.**	An ALIGNMENT is a reduced COST due to a FORCE shared between at least two GOALs.   
**c4.23.**	A relationship (RLTP) is a GOAL about PPL.   
**c5.23.**	A BET is a PLAN template for reconciling REALITY with CHUD, to accomplish GOALS.  
**c5.41.**	CHUD is an acronym for assessing the reality of GOALs: COSTs, HABITs, UNKNOWNs and DOUBTs.  
**c5.43.**	A HABIT is the historical average of your actions and their by-products.
**c5.44.**	An UNKNOWN is a FORCE (especially out of your CONTROL) that makes your PLAN wrong.
**c5.48.**	A DOUBT is a source of predictable or nameable UNKNOWN, for example, "denial" or "anxiety".  
**c6.15.**	A STUDENT is a ROLE with IDEAS from EXPERIENCE toward selfish GOALS.  
**c6.39.**	A READER hears a perspective to note their own reaction to its truth-value.  
**c6.64.**	A WRITER invests TIME and energy to map feelings onto WORDS.  
**c6.73.**	An INSTRUCTOR is a READING ROLE, and enforcing BETs on STUDENTs' PLANs.  
**c7.20.**	A WORD is a BET for simulating (direct attention to) truth (reality) or falsehood (fantasy).  
**c7.23.**	A PLAN is a BET on a winning arrangement of WORDS that result in the GOAL.  
**c7.47.**	A SCIENTIST BETS new CONTENT against the UNKNOWN, evaluated for their net gain for NORMs.  
**c7.48.**	A RESEARCHER is a SCIENTIST WRITER, a data-collector and hypothesis tester.   
**c7.49.**	A SCHOLAR is a SCIENTIST READER, curating toward theory development and COMM.  
**c8.19.**	A LESSON is an ordered set of prompts, usually three to four, up to 60 minutes.
**c8.33.**	NOTES are general PLANS for REVISION. (Available on request.)  
**c8.37.**	A RECIPE is a DOC format that PRIs CONTENT (IDEAS and LINKS) over STYLE.  
**c8.45.**	COMM is the exchange of WORDS between PPL.   
**c8.54.**	An EXAMPLE is a particular experience of the real world.   
**c8.55.**	A WORD describes a set of similar experiences.   
**c8.61.**	VERSIONs are variations of STYLE on a identical CONTENT, implicitly in temporal order.   
**c8.62.**	A PLAN for a DOC is an earlier VERSION of the (same) final DOC.  
**c8.65.**	PITCH is DOC STYLE for why to READ.   
**c9.58.**	PPL are different VERSIONs of each others' PRI (WRITER and READER are different, too).

