---
output:
  word_document: default
  html_document: default
---
Two parallel versions exist.
2022-06-21-1410 presented first, most ingested in second as of
- 2022-06-27-2044
2021-10-07 presented second as 'Thoughtrepair'
- posted there as 'proper discourse' draft

## notes while talking to rebecca2
2022-06-27-2317

the core is the irony. its the point.
the dark and angular means are part of the point's shape.
you see they are not the point, as if you can thusly dodge the blow,
but all you see is the reflection of your face on the face of the blade aimed at you.
worse yet if the blade isn't aimed at you but you think so.

so to reject then is to assert NOT comm;
a person wants to talk of themselves, but more
they want to be liked as themselves, without words.
when someone says something dumb, say, "I love you".

### Abstract and Starting assumptions  
1. All utterance to self or another is the result of an implied imperative to yourself, "THINK", (at least) for your own PRI.
2. COMM, the exchange of WORDS between PPL of different PRIs, is by default GOOD and CLOSER. To SAY a WORD is to BET on a PRI of potential GOOD for the other person. Each time one responds (i-the WORD-NEXT), they imply consent (LET) that COMM is worthwhile for one's personal PRI and to a shared PRI for both (COMM-PRI). Supposing such a shared PRI exists, then the POINT is its MOMENT.
3. The following COMM example tries to expose this nature with the purpose of defining the scope and purpose of GOOD-REF in COMM.
4. For purpose of general guidance, the named REFs which are labelled pejoratively as "BAD" or "STYLE"--such as PATRONIZING, SARCASM, SADISM or HUMOR--are general. Other ones such as XREF, EVIDENCE, HYPOTHETICAL may be charitable. In some instances these REFs may be the BEST. 
5. However, here I attempt to expose that even this possibility is dubious, because the POINT is rarely less important than manners of conveying it. Moreover, neither incidental nor deliberate usage of manners should supersede the POINT.



## THOUGHT REPAIR VERSION

This is about what we have conversations for, and what we do in addition to conversation. You will no doubt have no trouble thinking of examples of conversation I am not talking about. You may even believe you have no interest in having a conversation like I am talking about. This assertion is going to seem surprising, given that I am attempting to describe any and every conversation that has a clear purpose and finite time. By the end I hope to have made the case for this paragraph to be deleted, not because it is patronizing, but because it is irrelevant.

### Commentary as filibuster

"You don't need to be so patronizing. Are you serious? Do you really mean that? Could you clarify your question? You have no right to say that. You're being hypocritical."

"Listen, I only want to have to say this once in my life, about the fact that you're playing a convention to call me on how I'm talking to you. I think we'd both agree that we came together to talk for the purpose of reaching a shared understanding.

"What I just said, that you found patronizing, we can evaluate for its patronizingness, and also for its contribution to shared understanding."

You: "But it's reasonable that the best dialog contains at least a modest amount of respect."

I: "What better show of respect than sticking steadfastly to the point, attempting to increase shared understanding? Is there nothing of merit to comment on, instead of commenting on the style you don't like?"

Y: Perhaps, but not before an agreed civility.
I: For example? Or can you repeat the main point I said, without its patronizing? If you say you cannot HEAR my point, then you are in dangerous waters, imposing your recipe for CAKE on my offering of moldy food. 

Say what causes me to make the point I intended and advance our dialog, AND accomplish the point you're making without any sacrifice to the speed and precision of the first, agreed agenda. Why do you insist on two agendas? 

The greatest benefit of doubt I can give you is to assume that ALL appeals you make to your own feelings are either:
precisely FOR our shared goal,
entirely for yourself, a unique unfair disadvantage to you,
or worse, sharing your feelings are the only thing you want me for.

And then I think you have brought us to the exit of cooperation, and have let me know that you are here solely for your own PRI.

### Pity peanuts  

Asking for a modicum of politeness is like demanding I bring peanuts to share before arguing with you on who will make the dinner and how. I am sitting here, working toward our resolution. Once we've started working on a meal we agree worth having, the etiquette of all peanuts is moot. I may finger the nuts, eat them all, or complain about them, but as long as our chat advances, there are no peanuts to be concerned of.

after we have already started,
why is there any politeness you
insist on instead of responding with your own honest contribution to our agenda?

then i too demand an ammendment to the basis of dialog for a shared purpose.
unlike my patronizing (alleged, unshared purpose),
for every second we grant your non-sequitor interruption, it, is a second of insult to our agreed subject.

### hips don't lie.

As long as there is substance in the speech I advance, that contributes to shared understanding, don't take up your time to advance the conversation, by telling me you're distracted by the way I move my hips.

if you need to feel a gesture of good faith from me in order to argue,
then take off your pants and let me stimulate your genitals.

### No, YOU'RE gas-lighting
In fact, I don't think what I said was patronizing. We might discuss it. Or we might discuss what we came together to discuss in the first place.

I too want an amendment to the conversational rules of engagement. Do not insult our desire to resolve the primary issue with an off-topic interruption about patronizing, or conversational rules of engagement. 




Be prepared to tell me how I might have made the exact point I intended, as quickly and clearly or more, yet less patronizing. That isn't enough to warrant mentioning it. Tell me how I might have made the exact point, such that you would have understood my ideas better, responded more quickly and clearly, in a way that sped up our resolution. Do tell me that you're not intimidated to give a direct answer to the content of my patronizing remark.

If you need to feel a gesture of good faith from me in order to argue,then take off your pants and let me play with your genitals until you orgasm.

The more important you find your feelings in this moment, the more I understand your personal feelings, during the limited opportunity to come to a shared understanding, are centrally important to your view on whatever it is we were talking about in the first place. What were we talking about before you tried to stall us, again? 

Before you commented on my grammar, or the imprecision of my words, or about your Grandma's thoughts. 

A conversation I have with nobody, every time.

### Epilogue

"Other drivers", you're thinking, "right?" No, you're not. Actually, yes you are. I'm talking about you, too. You're an "other driver", too. Now, if you commute by bicycle, then you're cool. I won't patronize you.

## war words
when arguing an enemy, or a problem.

Suppose we've come together to make and eat a meal and I am eating the ingredients while we debate what to make.
(First, I'm performing the null hypothesis, no preparation. Second,)
Still, as long as there's more meal to be made than I've eaten, it is in your interest to either expedite the negotiation.

### battle ready
Respect is as relevant as a bow before before commencing battle. If we have unique perspectives or disagreement worth sharing and resolving the best respect I can give you is a timely volley toward a resolution, after which I can show you the respect a shared understanding demands,in the most fair and agreed upon manner.
///vs//

To flaunt or repair 'respect' is like 
a military parading or "standing fast" before a battle.
if we have a communication priority,
the best respect i can give you
is a volley toward that specific goal.
afterward, perhaps you'd like to set up some time with me,
to discuss the benefit of respectful discourse.
i can show you the respect you're demanding
in the most fair and agreed upon manner.
i might not think what i said was patronizing, and 
we might debate it.
but right now, nothing is a service to you and i, that is not discussing what you and i have AGREED is our communicative priority. 
