Glossary

## c2.SELF

38.	A GOAL names an ideal future reality, comprises a PLAN to increase its likelihood, associated with CHUD.
44.	A PLAN is any combination of WORDS where the writing or reading of them aims 
to improve the chance or decrease the COST of achieving your GOAL.
49.	What is materially required--muscle energy, cash, brain power--is COST.
51.	COST is any action that has a direct exchange.
56.	FOOD is the necessary and sufficient material to satisfy these needs.
57.	CAKE is anything (else) fulfilling, that you are inclined to pursue, including the reason for living.
58.	SELF is what's necessary and sufficient for FOOD and to maximize BET outcomes ([c5.28][BET]).
59.	HOME is the collection of materials and TOOLS needed for SELF.
62.	HOME also includes all physical material and resources you own, including 
MONEY, and environment and basis for HABITS.

## c3.PRI

33.	The GOAL of PRI is to manage the set of GOALS in your life.
38.	TIME is the constant (or denominator) for FORCES, FORGETTING, PRI, and LIB. 

## c4.PPL 

9.	Money is traded for maintenance of, or insurance for SELF and CAKE, like apples, miracle medical procedures, and a toilet to take your poop somewhere else.
10. WORK is performing a specific task on a collective garden, like an institution's in exchange for money.
13.	NORMS are all actions assumed of (or about) the "average" person. They are the web of FORCES of all actions of all PPL, including WORK, religion, popular attitudes, and DOUBTS.
16.	Language, agreed usage of WORDS, is made from NORMS.
17.	NORMS push against individuality.
20.	A FORCE is any cause of change. A FORCE underlies every action involved in a GOAL, yours or otherwise. There are forces within your control, and forces outside.
21.	MAINTENANCE is the COST of FORCE to neither move toward nor away from a GOAL. 
22.	ALIGNMENT is when NORM or natural FORCE causes your GOAL to be more likely.	To ALIGN is to adjust your GOAL to be more like another force, 
usually one acting against your GOAL. 
23.	Relationships (RLTP) are GOALS about PPL (PPL). 

## c5.BET
23.	A BET is a PLAN template for reconciling REALITY with CHUD, to 
accomplish GOALS.

41.	CHUD encompasses the changes in you, the world, and your GOAL for 
you to achieve it.
42.	COST [c2.51][SELF]
43.	HABITS are your dominant tendencies (FORCES). 
43.1.	HABITS are your most likely and reliable FOOD or CAKE actions.
44.	If you have not arrived at the GOAL, there are UNKNOWNs. 
48.	DOUBTS are predictable failures of estimating Reality, PLANs and UNKNOWNs.


## c6.ed

15.	Students are PPL with IDEAS from EXPERIENCE toward selfish GOALS.
39.	A reader is a listener and observer.
64.	BET on WORDS. A writer invests TIME and energy to map feelings onto WORDS.
66.	Revisions also make you a WRITER. When you revise WORDS (yours or others') 
to maximize your BET, you are a writer.
73.	An instructor READS, and enforces BETs on LINKs toward a PLAN.


## c7.WORDS
20.	Every WORD itself is a BET on hypotheticals, which can be true (reality) or false (fantasy).
23.	A PLAN is a BET on a winning arrangement of WORDS that result in the 
GOAL.
24.	WORDS efficiently simulate possible worlds. 


47.	A scientist works to win BETS against the UNKNOWN. They are a 
professional writer, evaluated on two metrics:
    1.	For their new CONTENT. 
    2.	The net benefit on GOAL outcomes.
    
48.	A scientist-researcher is a WRITER, a data-collector and hypothesis tester. 

49.	A scientist-scholar is a READER, curating toward theory development and COMM.

## c8.REVISION

19.	LESSONS are an ordered set of prompts, usually three to four, up to 60 minutes and 250 WORDS. 

33.	NOTES are general PLANS for REVISION. (Available on request.)
37.	The RECIPE format highlights the IDEAS and LINKS of your point and minimizes excessive STYLE.
45.	COMM is the exchange of WORDS from oneself to another. 
48.	The problem of COMM is the difference in meaning between READER 
and WRITER of the same WORD. 

54.	The real world is particular; each experience is an EXAMPLE. 
55.	A WORD describes a set of similar experiences. 

61.	Versions describe identical CONTENT with difference in STYLE between 
them. 
62.	A PLAN for a DOC is an earlier VERSION of the (same) final DOC.
65.	A DOC's arguments for why to READ it are a STYLE called PITCH. 

## x
PLANs for each Definition;
- GOOD vs BAD

