
# (APPENDIX) Lessons {-}  


# Zero or One  

As a human you are endowed with words.
Too much so. The pervasive impulsivity of putting-to-words means you are often deprived
of un-judged, raw feelings of reality.
For a moment, forget those words.
Let's engage with the manners of communicating
using a vocabulary of 2.

Please answer each question with "0" or "1".
Do not dwell on any one question.
You may assume anything you like about your words,
but the point of this exercise is to think about what is true without words, and how you might accept (or not)
what another can or cannot know about you without words.
 
1.  Which are you: 0 or 1?
2.  If the person who knew you best guessed your answer,
    what would they report? 0 or 1?
3.  What would you tell them you are?
4.  What would the last dog you encountered say you are?
 
How do you feel about
5.  lunch today?
6.  the chair you are sitting in?
7.  your fingers?
 
8.  Where do you live?
9.  When were you born?
10. What makes this question so simple that you can answer it
    with 0 or 1?
11. Is lying, or hoping, or reminiscing 0, or 1?
12. Have you been telling the truth to these questions?
13. Are you honest with yourself?
 
14. Are you here?
15. Do you know?
16. How do you know?
17. What would it look like if you didn't know?
18. What if you *don't know* if you know?
 
19. What are you certain of?
20. Is this annoying or interesting?
21. Are you ready to use words, yet?
 
22. Imagine you didn't know of language beyond 0 or 1.
    You didn't know a deeper connection with others was possible.
    The chance to respond to the following question is
    your 15 minutes of fame to the universe.
    What is your one bit of say,
    written on the ledger next to your existence, or
    on your tombstone: 0 or 1?
 
23. What's your average score? 0 or 1?
24. Has this been insightful?
 
If you wrote 1 for 24, congratulations.