# Student in School

## Part 1: 10 year plan
This is a lesson in curriculum writing.
Imagine a perfect course exists,
designed to teach you
to fulfill your specific ambitions.
 
What are your top 4 goals for
the next 10 years?
you could work on any part of yourself,
move toward any goal you want.

### **Task 1. 3m, 40w.**
 
list four goals,
Each no longer than 10 words
 
### **Task 2. 3m, 40w.**
Your current program requires things your 10 year plan does not.
Courses impose a number of
conditions on your life:

1.  Fixed time: courses
2.  Variable time: assignments
3.  Uncertain time: studying
 
List four objectives, goals, course or program requirements that are
most on your mind right now.
Whether most frustrating, or most critical
to you, even 'impress my professor'.
 
### **Task 3. 5m, 50w.**
 
Spell out the intersection between the two lists.
Think of how each goal in the second list
directly influences (or not) your 10 year
objectives.
 
Explore the main ways these two lists relate.
 
For example,
1.  If I don't get a B, I won't keep my scholarship, and will have to
    get a job which will likely lower all my grades.
 
 
### **Task 4. 15m, 100w.**
 
What is the least you can do toward the course requirements and still achieve your long term goals?
Consider cutting the work from list two,
that doesn't overlap with one.
 
Examples:
 
1.  Graphic design is fun but not necessary. I could drop it and
    still graduate.
2.  If I get a D, I'll still pass, graduate, and be able to start my own
    business.
 
Add 100 more words to your description.
 
### **Task 5. 15m, 50w.**
 
Negotiate ways to make direct progress on your first list while fulfilling the second list.
 
For example, my personality class requires a term paper.
To align with my business goal, maybe the professor will let me write
on "personality traits of Entrepreneurs."
 
Add up to 50 words, and revise.


## Part 2: Two week plan

51.	Often you will define experiences by your priorities and immediate 
desires.
52.	Experiences out of line with your desires are dreaded, and those in 
line with them are eagerly anticipated. 
53.	For example, a college student dreads midterms and anticipates spring 
break. Each are about one weeklong, yet the feeling of TIME passing 
and the motivation to engage with challenges are very different. 
54.	Anticipations can create disappointment, so reduce speculation, 
especially its harmful effects on you.
55.	Do more of what you like when you most need it, try to appreciate 
what you dread, as it is, including the suffering.
56.	Task 1. 4m, 50w. List 4 GOALS to accomplish for midterms, before
spring break
57.	Task 2. 4m, 50w. List 4 GOALS for the best spring break you can 
imagine.
58.	Task 3. 15m, 200w. There are only so many hours in a day. What 
aspects of SELF-care can you incorporate during your midterms to 
improve your sanity, and hopefully your midterm performance? 
59.	We know what happens if you don't. You're staring at your phone; 
you're reading random articles on the internet and wasting TIME. 
60.	Let's take that same honest realism and intentionally PLAN better 
alternatives: instead of garbage breaks, how about spring breaks? 
61.	In what strategic ways can you get a head start on your spring break 
GOALS, as a form of SELF-care and therapy during your marathon of 
midterm WORK?
62.	Write out your midterm GOALS with SELF-care and/or spring break 
strategically built in.
63.	Task 4. 15m, 200w. Now imagine that spring break more fully. You're 
spending TIME on one of your GOALS, when suddenly you remember 
something, you need to do for midterms. 
64.	Maybe you get an email from your instructor or boss, or there's a 
project that looms large. 
65.	What are you going to do to be okay with this intrusion? Would it help 
to allow some TIME to WORK on it, or is it vital that you embrace your 
needs and resist any urge to do WORK? 
65.1.	Regardless of how you might ideally respond, PLAN for SELF-
compassion for when you might unexpectedly struggle 
emotionally. 
65.2.	Write out your spring break GOALS with midterm GOALS 
incorporated.
