---
editor_options: 
  markdown: 
    wrap: 72
---

# Lesson: DOUBT

1.  Imagine receiving the perfect email that meets your needs; addresses
    your fears, frustrations, paralysis. One that gives you the guidance
    only you could dream of.

## Task 1. 4m, 40w.

2.  List things the email should include feelings, tangible things,
    states, WORDS of wisdom, anything you need to hear.

Task 2. 4m, author name, revise.\
3. Consider who could write this: a boss, a best friend, a stranger. Add
an author and revise as needed.

## Task 3. 15m, 200w.

4.  Now write that email. Don't worry about how or why "they would say
    this." Focus on making sure the letter covers the things you NEED to
    hear.

## Task 4. 2m, "your name".

5.  Plot twist. Russia sends long range missiles that take out U.S.
    infrastructure including the internet. The government issues a full
    lockdown, and you're home alone without Netflix.\
6.  Two days in, an email appears on your computer.
7.  It's the letter! How is this possible? Slowly you realize, you must
    have written this letter. You did!
8.  Add these WORDS at the bottom of your letter:
9.  "Respectfully, (your name)"
10. Read what you need to hear, in the true leader's voice: yours.

## Task 5. 15m, 0w.

11. Your original author may have had the authority, resources, or
    information you don't. For example, "Here's 20 thousand dollars to
    build your classroom."
12. Revise to make the letter practical.
13. Tip 1: For resources you don't have-- money, TIME, influence--
    accept that indeed, you do not have power over these things, give up
    attempts to control, and welcome your feelings.
14. Tip 2: For guiding your behavior--decisions, actions, confidence--
    give permission to take action.
