revision-auto-e
x-is this what leibnitz went for

## resolve condition and cause
begin with a link claim.
  ev1-"john-happy if john-full."

1.move conditional to first clause

  ev2-"if john-full john-happy."
2.reduce 'if' to implied.
  ev3-"john-full is john-happy."
the order is itself the conditional
for the conservative translation.
but in fact, a conditional is quite a strong assertion.

3.escalate cause to action (plan).
  ev4-"fill john for happy."
this renders usable action,
easier rejection or promotion of the value.

(4. or reject cause for correlation
  ev5-"john-f full-f-happy; happy-f-full"
if causal is true, the revision opportunity will be salient.)

## plan first
(2) features 
- like happiness
are often a good goal, 
but not always.

(3)move the bad
from goal to plan,
and remove the goal.
let the goal be implied as
universal and perfect.
  ev6-"fill john"

ev6 is a plan,
and plans are my style for communicating links.
see ch8 for more on links.



## 2-prior versions
### v1
"given the merit of happiness".
*but the next point will illustrate we dont need to assume this, so I shouldn't set up something that i will contradict.

### v2
first we assume
while features are variously worth optimizing,
one of which is happiness
in other words, happiness 
is often a good goal, 
but not always

## 3-prior versions
v3tu-2022-06-12-1201
v3td-2022-06-12-1205

### v2
v2tu-2022-06-12-1156
v2td-2022-06-12-1200
we write and revise toward
the perfect goal.
- only

a universal goal, then
need not be stated.
assume the purest and strongest form
of 'benefit' at all times,
and where something falls short,
reveal its particular limits
i-move (potential) limits from goal to plan.
  e6-"fill john"

### v1
v1td-2022-06-12-1156

then we admit happiness is an imperfect construct,
and we are interested in the perfect one.
or to put otherwise,
we write and revise toward only what truly elevates.

a universal goal, then
need not be stated.
let us assume the purest and strongest form
of 'benefit' at all times,
and where something falls short,
let its limits stand in the particular,
for labeling when necessary.
  e6-"fill john"

