---
title: "10. IBC Culture"
output:
  word_document:
    reference_docx: template.docx
  pdf_document: default
version: 2.0.5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1400w


## Roles 


A role is a set of attitudes and actions.  
  
(See READER, Ch X)
### WRITE  

BET on WORDs.
A writer invests time and energy   
to map feelings onto words.   
  
Good writing is discovering,   
curating, and applying insight.   
Bad WRITING has an author; *ad hominem*   

Revisions also make you a WRITER.
When you revise words (yours or others') 
to maximize your BET,
you are a writer.


Separate thought and self (author),   
by BETTING explicitly.   

State your assumptions,   
do not justify them.   
-is-STYLE-bad

Replace \"I am.\" with tag words.  
  
Strive for COMM-CONTENT and brevity;  
Write only valuable BETs, or
WORDs that manifest valuable BETs.
Prioritize understanding over original writing.

WRITING for LIB-PPL, 
relatable, depersonalized, objective words,
minimizes ROT, maximizes PLAN utility.

### PEERs  

Forget *who* provides REVISION and how much.   
Get answers from others.

### Student

Students are PPL with
IDEAS from EXPERIENCE toward 
selfish GOALS. 

Lessons depend on 
students' prior knowledge.   

A STUDENT 
  
1.  has a goal that can be better named and planned.  
2.  requires time away from BETTING.  
3.  admits not knowing but capable.

Students learn
to represent their knowledge in words;   
to prefer better, alternative words.  
 
sees the impersonal as more reliable   
both for selfish GOALS and  
social ones. 

A bad student studies 
to avoid action, or 
for its own sake.

A Student WRITES IDEAs and GOALs
to their INSTRUCTOR.

### Instructor  
A guardian of 
1.True IDEAs expressed in COMM, and
2.WRITER of a general PLAN (this book).

An instructor READS, and enforces 
BETs on LINKs toward a PLAN. 

1.Minimize student effort and time to write. 
2.READ for 
  - cognitive biases, 
  - illogical appeals, and  
  - imprecise language, and  
  WRITE feedback that is 
  - dispassionate and neutral, yet
  - invested and True.  
3.Reward defense of arguments based on 
  (Truth:) REALITY, SELF, and VALUES.   
4.Reward IDEAS shared (vs personal).

### RLTP--Peers

Peer review is a powerful learning tool.

The peer WRITER   
works with uncompromised objectivity,   
and liberty to employ Truth,   
however subjectively "harsh".  

### Scientist    
  
A scientist WORKs to win BETS against the UNKNOWN. 
They are a professional writer, 
evaluated on two metrics:  
  
1.  For their MEMES of CONTENT.  
2.  The net benefit of their MEMES on GOAL outcomes.  
  
A scientist-researcher is a WRITER,   
a data-collector and hypothesis tester.   
A scientist-scholar is a READER,  
curating toward theory development and COMM.  
  
### Scholar  

a professional READER and 
Peer-Reviewer,  
especially in curating the Scientist's insights.  

evaluated by repost statistics   
(others as readers),  
akin to evaluating twitter users by their retweets.  



## Plans
imported

### BETS and CHUD
(BET) Name:  
    -   a step in your PLAN,  
    -   a **deadline** to achieve it, and  
    -   the C.H.U.D. for that duration.

Attempt to succeed, and document your efforts.

When the deadline arrives, take stock.  
    -   Revise your PLAN and CHUD based on your effort.   
    -   Start another BET or GOAL.

### FORCES
name CHUD; better to know them
Study how forces work against you.
ALIGN GOALS with FORCES

### UNK
Explore and learn where the line of control is,  
Expand control productively, and  
Let go of unhelpful attempts to control.  

### PLANS
Do not write PLANs you won't follow.
To assess PLANs (e-in this book) see READING
clarify planning and improve your expectations

Keep a clean HOME, and LIB

### PRI	
group GOALs by shared actions, places, or times.  
Make/group/keep, 
order, reduce in the order presented in Figure 4.
"A place for everything, everything in its place"

ALIGN SELF and VALUE
Adopt all your goals to REALITY ("above", e-you will die). 
Think about the sum of your GOALS, 

### TIME
Do not ignore time
Estimate durations accurately
for GOAL accomplishment

### SELF	
Identify and revise VALUES that are 
sufficient but not necessary for SELF. 

study time to learn reality, SELF, and the LINK between the two.
Ask/reflect/study: Does the benefit of a GOAL outweigh the cost of time? 
Ask what it would take to change (if possible), and whether change is worth it.  
Separate what you need from what you want.   
- master the SELF (survive well).

Build routines for  
- health and fitness,  
- physical safety (shelter),   
- a sound mind,   
- healthy relationships.  

Satisfy HOME, and SELF GOALs 

### SELF-W
speak the truth or shut up.  
Use them for decisions, not emotions.   
Use to facilitate your life PLAN and 
stop talking for other reasons.  "

### PPL
Pick WORK and RLTPs that maximize your other PRIs including possibly one that maximizes time and money to apply to other PRIs. 

i-Pick friends the same way.  
Consider your actions and choices about people carefully.  
Maximally ALIGN with NORMS with least compromise to PRIs.  
align (get along with) people.

### PPL-W
Do not use a word that is more of a Lie

assert boundaries against 
exaggerated words or
unreliable time (scheduling)


### NOTES
Add structural consistency to make LINKS more explicit.
edit/apply these techniques as a form of active READING.

### Agreement
On acceptance you will attend 
an in-person immersive experience.

Our bodies resist discomfort.   
You won't learn    
unless you cannot escape needing it;
in a dedicated environment   
that fosters acquisition,
minimizes interference.

7- or 30-day experience,  
meals and lodging included.  
There will be no phone or internet access.  

In exchange, students are to
0.provide two minutes of product  
  for every minute of learning. 
  a.content toward others' learning (IBC).  
  b.the application of their learning.  

Dedicate to identity growth. 
Be:  
  
1.  Quiet, except when tasks require verbal response.  
2.  Receptive to work and feedback provided by the instructor.  
3.  Committed to producing genuinely inspired ideas, working quickly,  
    and seeking improvement.  
4.  Respectful that all are equal in voice, and aim to describe  
    solutions with collective values.  
5.  Receptive and responsive to prompts and observations (from peers and/or  
    instructors) 
    especially CHUD, vague language, and cognitive bias.
6.  Motivated to describe solutions that benefit others, when possible, including peer-review  

As a result the student will
- eat, sleep, think, talk, and act differently.

Now,
what is it you'll learn?
The first subject is
to gain a clear picture of
what you think your life is. 



## manifesto

pull ibc-doc1-student rules

### better language / world

distrust words and ego
- taking nothing personally
- define everything empirically
  - comparison group/quantity (has unique outcome)
- remove / ignore style
- speak for reasons only
- idea > authorship (anonymity)
- read to rate to believe
- write to bet

#### speak 
speak / write
initiate / respond

limited in duration / words
- set by intended outcome

not at all
- when actions are known, needed
- when listening is needed

#### listen
listen / read
be with

when you need to learn / connect
- limited in duration/words needed
- to assess consent (agreement).

not when
- speaking values unadhered

#### repair
when listening to invalid speech,
after--repair
1m-gently with gestures
2m-briefly and clearly with words
3m-firmly with boundaries
5m-take polite action to end conversation

#### dialog / revise / anon
write what you bet
revise toward truth
- to max others' bets

radical anti-ownership of ideas
- edit for anyone with the authority of your autobiography
- for the benefit of the OP
- expecting only feedback

### actions
commit values to bets
- self + calling > cakes
- idea > xref
- bet > fact > belief > word
- action > money > words > thoughts

solutions to problems
- remove problem src or self from problem.
- accept that problem comes from other solutions
- revise those solutions (ie reuse)
- blitz solution
- eat, sleep better
- wake up: cold shower, pint of water, work out, deaf/blind hour, spend time with an ugly person

minimalism; align, revise and keep fit
- keep only hf things in smallest box possible
- keep clean
- keep routine (self) needs minimal
  - stuff, expectations, plans (movement)

### actions
"if" requires an action argument.
- (tethering hypotheticals)
