---
title: "3. The Garden: Preface"
output:
  word_document:
    reference_docx: template.docx
  pdf_document: default
version: 2.0.5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Preface to the Garden

The chapters on the Garden describe the key IDEAS of this book: the existential experience of being human--from the biological of eating and sleeping to thinking and meaning-making. The purpose is to illustrate the interdependence of mind and body (Garden-1), death and meaning (Garden-2), self and others (Garden-3).

In each chapter, two distinct parts, "The Garden" and "IDEAS and Plans", are two very different approaches to the subject matter. I'll first describe the three purposes as they relate to the Garden, then return to the second approach, "IDEAS and Plans", and the rationale for two approaches.

### Garden Overview  

"The Garden" is a description to be experienced as it is read, in that "pay attention" kind of way. I am talking to you, READER, in a language meant to be most familiar and accessible. 

Assumptions behind the garden are meant to be gentle. First is to *relocate* you to a familiar, but new reality. Not to ruin the fun, but the purpose is to be able to rebuild your actual reality and conditions of it in a controlled and explicit manner.

Your ability to imagine your garden shows how the mental world can be strategic and powerful in bringing clarity to your reality. 
However, your mind can also be idealistic in ways that set you up for failure and suffering. 

In this first Garden chapter,
the purpose is to make
a Garden with the specifics of 
your own life, identity, and ambitions.

The second chapter introduces
the critical theoretical assumption of this book.
This assumption allows a rich transformation
into yourself, and to connect with others.
It is that life is brief and you are mortal.

Together, chapters 1 and 2 give
all you need to conceptualize everything in your garden.
The third chapter examines
the consequence of
man-made existential universals.

Finally, today
human civilization is global,
meaning that there are human-made
technologies and expectations
that influence your life.
More personally,
you interact with trusted and strange people
very regularly.
The last chapter engages
the problems and solutions
related to the billions
you share your world with,
and what their pasts have done to 
your world and life.

### IDEAS and Plans  
The second part of each chapter
returns to reality.
"IDEAS and Plans" gives
clear, literal and concrete language 
to the key IDEAs and consequences (LINKs)
in "The Garden".

These sections
are written to make 
claims easier to evaluate
whether they're true to you or not.

Definitions for IDEAS (ALL CAPS) are always 
describing some sense(s) of 
what you already know by the same name,
but LIMIT which relevant senses.
For example "WORK" is about careers,
but not 'yard work'.

Generally, this is to give
IDEAS measurable, consequential meaning.
See the chapters on WORDS 
for more.

The rest of the section provides
a mixture of assumptions and observations,
typical contexts, applications and consequences.
This is written mostly imperative voice,
to foreground the intention.
The intention is to guide action,
and for you to easily evaluate
whether you BET the guidance is valid or not.

You can read more about this in "PLANS"

A special case of plans is a LESSON.
The LESSONS are much like "The Garden",
meant to activate 
relevant parts of your reality or beliefs,
in a way that applies
the IDEAS introduced.
They are exercises that
take between 10 and 60 minutes to complete.
You can read more about them in "SR".

### Summary

Why three chapters with
four styles?
The short answer is
ideas are multi-dimensional,
language is imperfect,
and you are a READER accostomed to
an unhealthy attitude
about consuming information.
It's not your fault.
Read WORDS, but especially the section, COMM.

